/**
 * Generated by "@vuepress/internal-routes"
 */

import { injectComponentOption, ensureAsyncComponentsLoaded } from '@app/util'
import rootMixins from '@internal/root-mixins'
import GlobalLayout from "E:\\小圆的前端学习\\vue项目\\blog\\node_modules\\@vuepress\\core\\lib\\client\\components\\GlobalLayout.vue"

injectComponentOption(GlobalLayout, 'mixins', rootMixins)
export const routes = [
  {
    name: "v-53ecae5b",
    path: "/blogs/category/ES6/092101.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-53ecae5b").then(next)
    },
  },
  {
    name: "v-f1694f66",
    path: "/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-f1694f66").then(next)
    },
  },
  {
    path: "/index.html",
    redirect: "/"
  },
  {
    name: "v-eb3e21ca",
    path: "/blogs/category/Vue/transferParams.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-eb3e21ca").then(next)
    },
  },
  {
    name: "v-706f62a5",
    path: "/blogs/category/markdown/front_matter.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-706f62a5").then(next)
    },
  },
  {
    name: "v-08f12e1b",
    path: "/blogs/category/Vue/vueInstall.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-08f12e1b").then(next)
    },
  },
  {
    name: "v-0b736d3b",
    path: "/blogs/category/ES6/121501.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-0b736d3b").then(next)
    },
  },
  {
    name: "v-d084738a",
    path: "/blogs/category/git/gitcmd.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-d084738a").then(next)
    },
  },
  {
    name: "v-8cfa1d18",
    path: "/blogs/introduce/introduce.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-8cfa1d18").then(next)
    },
  },
  {
    name: "v-7b572edd",
    path: "/docs/theme-reco/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-7b572edd").then(next)
    },
  },
  {
    path: "/docs/theme-reco/index.html",
    redirect: "/docs/theme-reco/"
  },
  {
    name: "v-6e772864",
    path: "/docs/theme-reco/api.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-6e772864").then(next)
    },
  },
  {
    name: "v-ef33d724",
    path: "/docs/theme-reco/theme.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-ef33d724").then(next)
    },
  },
  {
    name: "v-71201c64",
    path: "/docs/theme-reco/plugin.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-71201c64").then(next)
    },
  },
  {
    path: '*',
    component: GlobalLayout
  }
]