/**
 * Generated by "@vuepress/internal-routes"
 */

import { injectComponentOption, ensureAsyncComponentsLoaded } from '@app/util'
import rootMixins from '@internal/root-mixins'
import GlobalLayout from "E:\\小圆的前端学习\\vue项目\\blog\\node_modules\\@vuepress\\core\\lib\\client\\components\\GlobalLayout.vue"

injectComponentOption(GlobalLayout, 'mixins', rootMixins)
export const routes = [
  {
    name: "v-f1694f66",
    path: "/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-f1694f66").then(next)
    },
  },
  {
    path: "/index.html",
    redirect: "/"
  },
  {
    name: "v-6d1ffaaa",
    path: "/blogs/category/ES6/class.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-6d1ffaaa").then(next)
    },
  },
  {
    name: "v-c324f84a",
    path: "/blogs/category/ES6/deconstructionAssignment.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-c324f84a").then(next)
    },
  },
  {
    name: "v-b413a096",
    path: "/blogs/category/ES6/generator.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-b413a096").then(next)
    },
  },
  {
    name: "v-cb115a0a",
    path: "/blogs/category/ES6/letconst.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-cb115a0a").then(next)
    },
  },
  {
    name: "v-7b327136",
    path: "/blogs/category/ES6/promise.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-7b327136").then(next)
    },
  },
  {
    name: "v-282efa37",
    path: "/blogs/category/ES6/classExtend.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-282efa37").then(next)
    },
  },
  {
    name: "v-04e1f27b",
    path: "/blogs/category/ES6/operator.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-04e1f27b").then(next)
    },
  },
  {
    name: "v-df4fc68a",
    path: "/blogs/category/ES6/setMap.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-df4fc68a").then(next)
    },
  },
  {
    name: "v-6319ebfb",
    path: "/blogs/category/ES6/symbol.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-6319ebfb").then(next)
    },
  },
  {
    name: "v-46ad39a7",
    path: "/blogs/category/JavaScript/concat.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-46ad39a7").then(next)
    },
  },
  {
    name: "v-1b44d80e",
    path: "/blogs/category/JavaScript/includes.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-1b44d80e").then(next)
    },
  },
  {
    name: "v-ed2f2abe",
    path: "/blogs/category/JavaScript/jsStudyDay2.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-ed2f2abe").then(next)
    },
  },
  {
    name: "v-82516e3e",
    path: "/blogs/category/JavaScript/input.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-82516e3e").then(next)
    },
  },
  {
    name: "v-12396bc1",
    path: "/blogs/category/JavaScript/jsStudyDay1.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-12396bc1").then(next)
    },
  },
  {
    name: "v-1c09b6fa",
    path: "/blogs/category/JavaScript/reduce.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-1c09b6fa").then(next)
    },
  },
  {
    name: "v-543a3abe",
    path: "/blogs/category/JavaScript/spliceSlice.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-543a3abe").then(next)
    },
  },
  {
    name: "v-34331cbe",
    path: "/blogs/category/JavaScript/splitJoin.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-34331cbe").then(next)
    },
  },
  {
    name: "v-87e791c2",
    path: "/blogs/category/JavaScript/removeListener.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-87e791c2").then(next)
    },
  },
  {
    name: "v-33cd5b01",
    path: "/blogs/category/Vue/object....html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-33cd5b01").then(next)
    },
  },
  {
    name: "v-0a05322e",
    path: "/blogs/category/JavaScript/zoom.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-0a05322e").then(next)
    },
  },
  {
    name: "v-a0480e4a",
    path: "/blogs/category/Vue/atag.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-a0480e4a").then(next)
    },
  },
  {
    name: "v-9e11ec96",
    path: "/blogs/category/Vue/dynamicComponents.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-9e11ec96").then(next)
    },
  },
  {
    name: "v-62f1a805",
    path: "/blogs/category/Vue/normalize.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-62f1a805").then(next)
    },
  },
  {
    name: "v-62e5d1fb",
    path: "/blogs/category/Vue/pagenation.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-62e5d1fb").then(next)
    },
  },
  {
    name: "v-99c196ca",
    path: "/blogs/category/Vue/pi.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-99c196ca").then(next)
    },
  },
  {
    name: "v-14e0f813",
    path: "/blogs/category/Vue/vifvfor.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-14e0f813").then(next)
    },
  },
  {
    name: "v-eb3e21ca",
    path: "/blogs/category/Vue/transferParams.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-eb3e21ca").then(next)
    },
  },
  {
    name: "v-08f12e1b",
    path: "/blogs/category/Vue/vueInstall.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-08f12e1b").then(next)
    },
  },
  {
    name: "v-1051298a",
    path: "/blogs/category/Vue/vuescrollbar.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-1051298a").then(next)
    },
  },
  {
    name: "v-dda97aca",
    path: "/blogs/category/Vue/vueCss.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-dda97aca").then(next)
    },
  },
  {
    name: "v-13ccba1b",
    path: "/blogs/category/axios/axiospackaging.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-13ccba1b").then(next)
    },
  },
  {
    name: "v-59a7318a",
    path: "/blogs/category/echarts/fontsize.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-59a7318a").then(next)
    },
  },
  {
    name: "v-4a4ab1bb",
    path: "/blogs/category/echarts/shadow.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-4a4ab1bb").then(next)
    },
  },
  {
    name: "v-740468a1",
    path: "/blogs/category/markdown/toc.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-740468a1").then(next)
    },
  },
  {
    name: "v-4a68c542",
    path: "/blogs/category/css/alignment.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-4a68c542").then(next)
    },
  },
  {
    name: "v-d084738a",
    path: "/blogs/category/git/gitcmd.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-d084738a").then(next)
    },
  },
  {
    name: "v-2ca72d4e",
    path: "/blogs/category/html/flex.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-2ca72d4e").then(next)
    },
  },
  {
    name: "v-d9d5d85e",
    path: "/blogs/category/miniProgram/record1.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-d9d5d85e").then(next)
    },
  },
  {
    name: "v-71d07c7b",
    path: "/blogs/category/Vue/vuex.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-71d07c7b").then(next)
    },
  },
  {
    name: "v-34e4c326",
    path: "/blogs/category/miniProgram/conclusion1.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-34e4c326").then(next)
    },
  },
  {
    name: "v-7dc222fb",
    path: "/blogs/category/miniProgram/day1.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-7dc222fb").then(next)
    },
  },
  {
    name: "v-f15136a6",
    path: "/blogs/category/miniProgram/gitee.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-f15136a6").then(next)
    },
  },
  {
    name: "v-cb27ab8a",
    path: "/blogs/category/miniProgram/day3.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-cb27ab8a").then(next)
    },
  },
  {
    name: "v-36597502",
    path: "/views/others/message.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-36597502").then(next)
    },
  },
  {
    name: "v-0c17269b",
    path: "/blogs/category/miniProgram/day2.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-0c17269b").then(next)
    },
  },
  {
    name: "v-404148b3",
    path: "/blogs/category/miniProgram/request.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-404148b3").then(next)
    },
  },
  {
    name: "v-8cfa1d18",
    path: "/blogs/introduce/introduce.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-8cfa1d18").then(next)
    },
  },
  {
    name: "v-b1564aac",
    path: "/tag/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Tags", "v-b1564aac").then(next)
    },
    meta: {"pid":"tags","id":"tags"}
  },
  {
    path: "/tag/index.html",
    redirect: "/tag/"
  },
  {
    name: "v-ef9325c4",
    path: "/categories/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("FrontmatterKey", "v-ef9325c4").then(next)
    },
    meta: {"pid":"categories","id":"categories"}
  },
  {
    path: "/categories/index.html",
    redirect: "/categories/"
  },
  {
    name: "v-6319eb4e",
    path: "/timeline/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("TimeLines", "v-6319eb4e").then(next)
    },
    meta: {"pid":"timeline","id":"timeline"}
  },
  {
    path: "/timeline/index.html",
    redirect: "/timeline/"
  },
  {
    name: "v-e8d86dc8",
    path: "/tag/js/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Tag", "v-e8d86dc8").then(next)
    },
    meta: {"pid":"tags","id":"js"}
  },
  {
    path: "/tag/js/index.html",
    redirect: "/tag/js/"
  },
  {
    name: "v-3257dcde",
    path: "/tag/ES6/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Tag", "v-3257dcde").then(next)
    },
    meta: {"pid":"tags","id":"ES6"}
  },
  {
    path: "/tag/ES6/index.html",
    redirect: "/tag/ES6/"
  },
  {
    name: "v-7a5f6990",
    path: "/tag/JavaScript/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Tag", "v-7a5f6990").then(next)
    },
    meta: {"pid":"tags","id":"JavaScript"}
  },
  {
    path: "/tag/JavaScript/index.html",
    redirect: "/tag/JavaScript/"
  },
  {
    name: "v-322a45da",
    path: "/tag/vue/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Tag", "v-322a45da").then(next)
    },
    meta: {"pid":"tags","id":"vue"}
  },
  {
    path: "/tag/vue/index.html",
    redirect: "/tag/vue/"
  },
  {
    name: "v-32475d9a",
    path: "/tag/Vue/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Tag", "v-32475d9a").then(next)
    },
    meta: {"pid":"tags","id":"Vue"}
  },
  {
    path: "/tag/Vue/index.html",
    redirect: "/tag/Vue/"
  },
  {
    name: "v-184d950c",
    path: "/tag/HTML/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Tag", "v-184d950c").then(next)
    },
    meta: {"pid":"tags","id":"HTML"}
  },
  {
    path: "/tag/HTML/index.html",
    redirect: "/tag/HTML/"
  },
  {
    name: "v-980194ba",
    path: "/tag/axios/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Tag", "v-980194ba").then(next)
    },
    meta: {"pid":"tags","id":"axios"}
  },
  {
    path: "/tag/axios/index.html",
    redirect: "/tag/axios/"
  },
  {
    name: "v-119ea9c2",
    path: "/tag/echarts/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Tag", "v-119ea9c2").then(next)
    },
    meta: {"pid":"tags","id":"echarts"}
  },
  {
    path: "/tag/echarts/index.html",
    redirect: "/tag/echarts/"
  },
  {
    name: "v-e8d85932",
    path: "/tag/mk/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Tag", "v-e8d85932").then(next)
    },
    meta: {"pid":"tags","id":"mk"}
  },
  {
    path: "/tag/mk/index.html",
    redirect: "/tag/mk/"
  },
  {
    name: "v-323b9794",
    path: "/tag/css/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Tag", "v-323b9794").then(next)
    },
    meta: {"pid":"tags","id":"css"}
  },
  {
    path: "/tag/css/index.html",
    redirect: "/tag/css/"
  },
  {
    name: "v-32383f72",
    path: "/tag/git/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Tag", "v-32383f72").then(next)
    },
    meta: {"pid":"tags","id":"git"}
  },
  {
    path: "/tag/git/index.html",
    redirect: "/tag/git/"
  },
  {
    name: "v-28201f4c",
    path: "/tag/miniProgram/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Tag", "v-28201f4c").then(next)
    },
    meta: {"pid":"tags","id":"miniProgram"}
  },
  {
    path: "/tag/miniProgram/index.html",
    redirect: "/tag/miniProgram/"
  },
  {
    name: "v-79a2a91a",
    path: "/tag/introduce/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Tag", "v-79a2a91a").then(next)
    },
    meta: {"pid":"tags","id":"introduce"}
  },
  {
    path: "/tag/introduce/index.html",
    redirect: "/tag/introduce/"
  },
  {
    name: "v-7eff4a05",
    path: "/categories/ES6/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Category", "v-7eff4a05").then(next)
    },
    meta: {"pid":"categories","id":"ES6"}
  },
  {
    path: "/categories/ES6/index.html",
    redirect: "/categories/ES6/"
  },
  {
    name: "v-081e6844",
    path: "/categories/JavaScript/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Category", "v-081e6844").then(next)
    },
    meta: {"pid":"categories","id":"JavaScript"}
  },
  {
    path: "/categories/JavaScript/index.html",
    redirect: "/categories/JavaScript/"
  },
  {
    name: "v-7f0789a7",
    path: "/categories/Vue/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Category", "v-7f0789a7").then(next)
    },
    meta: {"pid":"categories","id":"Vue"}
  },
  {
    path: "/categories/Vue/index.html",
    redirect: "/categories/Vue/"
  },
  {
    name: "v-61150b86",
    path: "/categories/HTML/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Category", "v-61150b86").then(next)
    },
    meta: {"pid":"categories","id":"HTML"}
  },
  {
    path: "/categories/HTML/index.html",
    redirect: "/categories/HTML/"
  },
  {
    name: "v-2383bdd2",
    path: "/categories/axios/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Category", "v-2383bdd2").then(next)
    },
    meta: {"pid":"categories","id":"axios"}
  },
  {
    path: "/categories/axios/index.html",
    redirect: "/categories/axios/"
  },
  {
    name: "v-bd86249a",
    path: "/categories/Echarts/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Category", "v-bd86249a").then(next)
    },
    meta: {"pid":"categories","id":"Echarts"}
  },
  {
    path: "/categories/Echarts/index.html",
    redirect: "/categories/Echarts/"
  },
  {
    name: "v-029715c2",
    path: "/categories/markdown/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Category", "v-029715c2").then(next)
    },
    meta: {"pid":"categories","id":"markdown"}
  },
  {
    path: "/categories/markdown/index.html",
    redirect: "/categories/markdown/"
  },
  {
    name: "v-7efee0ca",
    path: "/categories/Css/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Category", "v-7efee0ca").then(next)
    },
    meta: {"pid":"categories","id":"Css"}
  },
  {
    path: "/categories/Css/index.html",
    redirect: "/categories/Css/"
  },
  {
    name: "v-7f008cdb",
    path: "/categories/Git/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Category", "v-7f008cdb").then(next)
    },
    meta: {"pid":"categories","id":"Git"}
  },
  {
    path: "/categories/Git/index.html",
    redirect: "/categories/Git/"
  },
  {
    name: "v-7efe64ca",
    path: "/categories/CSS/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Category", "v-7efe64ca").then(next)
    },
    meta: {"pid":"categories","id":"CSS"}
  },
  {
    path: "/categories/CSS/index.html",
    redirect: "/categories/CSS/"
  },
  {
    name: "v-e6d4b880",
    path: "/categories/miniProgram/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Category", "v-e6d4b880").then(next)
    },
    meta: {"pid":"categories","id":"miniProgram"}
  },
  {
    path: "/categories/miniProgram/index.html",
    redirect: "/categories/miniProgram/"
  },
  {
    name: "v-5bf9d5be",
    path: "/tag/js/page/2/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-5bf9d5be").then(next)
    },
    meta: {"pid":"tags","id":"js"}
  },
  {
    path: "/tag/js/page/2/index.html",
    redirect: "/tag/js/page/2/"
  },
  {
    name: "v-aa66d5ac",
    path: "/tag/Vue/page/2/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-aa66d5ac").then(next)
    },
    meta: {"pid":"tags","id":"Vue"}
  },
  {
    path: "/tag/Vue/page/2/index.html",
    redirect: "/tag/Vue/page/2/"
  },
  {
    name: "v-1fca9b94",
    path: "/categories/Vue/page/2/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-1fca9b94").then(next)
    },
    meta: {"pid":"categories","id":"Vue"}
  },
  {
    path: "/categories/Vue/page/2/index.html",
    redirect: "/categories/Vue/page/2/"
  },
  {
    path: '*',
    component: GlobalLayout
  }
]