/**
 * Generated by "@vuepress/internal-site-data"
 */
export const siteData = {
  "title": "夏鸣予的博客",
  "description": "永远怀着一刻真诚与善良的心",
  "base": "/",
  "headTags": [
    [
      "link",
      {
        "rel": "icon",
        "href": "/favicon.ico"
      }
    ],
    [
      "meta",
      {
        "name": "viewport",
        "content": "width=device-width,initial-scale=1,user-scalable=no"
      }
    ]
  ],
  "pages": [
    {
      "title": "Home",
      "frontmatter": {
        "home": true,
        "heroText": "夏鸣予",
        "tagline": "无奈涧水何,喧喧夜鸣石。",
        "bgImageStyle": {
          "height": "450px"
        },
        "isShowTitleInHome": false,
        "actionText": "Guide",
        "actionLink": "/views/other/guide",
        "features": [
          {
            "title": "Yesterday",
            "details": "开发一款看着开心、写着顺手的 vuepress 博客主题"
          },
          {
            "title": "Today",
            "details": "希望帮助更多的人花更多的时间在内容创作上，而不是博客搭建上"
          },
          {
            "title": "Tomorrow",
            "details": "希望更多的爱好者能够参与进来，帮助这个主题更好的成长"
          }
        ]
      },
      "regularPath": "/",
      "relativePath": "README.md",
      "key": "v-f1694f66",
      "path": "/",
      "lastUpdated": "1/19/2022, 4:27:50 PM"
    },
    {
      "title": "ES6学习之路(一) Generator函数",
      "frontmatter": {
        "title": "ES6学习之路(一) Generator函数",
        "date": "2022-01-5",
        "tags": [
          "ES6",
          "JavaScript"
        ],
        "categories": [
          "ES6"
        ]
      },
      "regularPath": "/blogs/category/ES6/generator.html",
      "relativePath": "blogs/category/ES6/generator.md",
      "key": "v-b413a096",
      "path": "/blogs/category/ES6/generator.html",
      "headers": [
        {
          "level": 2,
          "title": "前奏",
          "slug": "前奏"
        },
        {
          "level": 2,
          "title": "主题",
          "slug": "主题"
        },
        {
          "level": 3,
          "title": "主角",
          "slug": "主角"
        },
        {
          "level": 3,
          "title": "next函数传参",
          "slug": "next函数传参"
        }
      ],
      "excerpt": "<div class=\"custom-block tip\"><p class=\"title\"></p><p>这是一篇关于ES6generator函数的知识o(￣▽￣)ｄ</p>\n</div>"
    },
    {
      "title": "让我的Vue得到重生(四)-Vue的动态组件",
      "frontmatter": {
        "title": "让我的Vue得到重生(四)-Vue的动态组件",
        "date": "2022-01-22T00:00:00.000Z",
        "tags": [
          "Vue"
        ],
        "categories": [
          "Vue"
        ]
      },
      "regularPath": "/blogs/category/Vue/dynamicComponents.html",
      "relativePath": "blogs/category/Vue/dynamicComponents.md",
      "key": "v-9e11ec96",
      "path": "/blogs/category/Vue/dynamicComponents.html",
      "headers": [
        {
          "level": 2,
          "title": "前奏",
          "slug": "前奏"
        },
        {
          "level": 2,
          "title": "主题",
          "slug": "主题"
        },
        {
          "level": 3,
          "title": "解释",
          "slug": "解释"
        },
        {
          "level": 2,
          "title": "使用keep-alive组件缓存部分动态组件",
          "slug": "使用keep-alive组件缓存部分动态组件"
        },
        {
          "level": 2,
          "title": "动态组件传参",
          "slug": "动态组件传参"
        },
        {
          "level": 2,
          "title": "小细节",
          "slug": "小细节"
        },
        {
          "level": 2,
          "title": "哲学时刻",
          "slug": "哲学时刻"
        }
      ],
      "excerpt": "<div class=\"custom-block tip\"><p class=\"title\"></p><p>这是一篇关于在Vue项目使用动态组件的文章o(<strong>￣︶￣</strong>)o</p>\n</div>"
    },
    {
      "title": "让我的Vue得到重生(-)-在vue项目中封装自己的插件",
      "frontmatter": {
        "title": "让我的Vue得到重生(-)-在vue项目中封装自己的插件",
        "date": "2022-01-07T00:00:00.000Z",
        "tags": [
          "Vue"
        ],
        "categories": [
          "Vue"
        ],
        "sticky": 3
      },
      "regularPath": "/blogs/category/Vue/vueInstall.html",
      "relativePath": "blogs/category/Vue/vueInstall.md",
      "key": "v-08f12e1b",
      "path": "/blogs/category/Vue/vueInstall.html",
      "headers": [
        {
          "level": 2,
          "title": "前奏",
          "slug": "前奏"
        },
        {
          "level": 2,
          "title": "主题",
          "slug": "主题"
        },
        {
          "level": 2,
          "title": "总结",
          "slug": "总结"
        },
        {
          "level": 2,
          "title": "鸡汤时刻",
          "slug": "鸡汤时刻"
        }
      ],
      "excerpt": "<div class=\"custom-block tip\"><p class=\"title\"></p><p>这是一篇关于在Vue项目中开发自定义插件的文章o(<em>￣︶￣</em>)o</p>\n</div>",
      "lastUpdated": "1/19/2022, 4:27:50 PM"
    },
    {
      "title": "在Vue项目中配合Animate.css + transition组件实现动画效果,给你的css加点料(add some water to your css)",
      "frontmatter": {
        "title": "在Vue项目中配合Animate.css + transition组件实现动画效果,给你的css加点料(add some water to your css)",
        "date": "2022-01-24T00:00:00.000Z",
        "tags": [
          "Vue"
        ],
        "categories": [
          "Vue"
        ]
      },
      "regularPath": "/blogs/category/Vue/vueCss.html",
      "relativePath": "blogs/category/Vue/vueCss.md",
      "key": "v-dda97aca",
      "path": "/blogs/category/Vue/vueCss.html",
      "headers": [
        {
          "level": 2,
          "title": "教程",
          "slug": "教程"
        },
        {
          "level": 2,
          "title": "哲学时刻",
          "slug": "哲学时刻"
        }
      ],
      "excerpt": "<div class=\"custom-block tip\"><p class=\"title\"></p><p>v-show + v-if + transition 组件 + Animate.css 给你的css加点料o(￣︶￣)o</p>\n</div>"
    },
    {
      "title": "让我的Vue得到重生(二)-Vue传参",
      "frontmatter": {
        "title": "让我的Vue得到重生(二)-Vue传参",
        "date": "2022-01-07T00:00:00.000Z",
        "tags": [
          "Vue"
        ],
        "categories": [
          "Vue"
        ]
      },
      "regularPath": "/blogs/category/Vue/transferParams.html",
      "relativePath": "blogs/category/Vue/transferParams.md",
      "key": "v-eb3e21ca",
      "path": "/blogs/category/Vue/transferParams.html",
      "headers": [
        {
          "level": 2,
          "title": "前奏",
          "slug": "前奏"
        },
        {
          "level": 2,
          "title": "主题",
          "slug": "主题"
        },
        {
          "level": 2,
          "title": "Params传参",
          "slug": "params传参"
        },
        {
          "level": 2,
          "title": "Query传参",
          "slug": "query传参"
        },
        {
          "level": 2,
          "title": "动态路径传参",
          "slug": "动态路径传参"
        },
        {
          "level": 2,
          "title": "Props传参",
          "slug": "props传参"
        },
        {
          "level": 2,
          "title": "Props对象传参",
          "slug": "props对象传参"
        },
        {
          "level": 2,
          "title": "props函数式传参",
          "slug": "props函数式传参"
        },
        {
          "level": 2,
          "title": "小细节",
          "slug": "小细节"
        },
        {
          "level": 3,
          "title": "1.params传参",
          "slug": "_1-params传参"
        },
        {
          "level": 3,
          "title": "2. query传参",
          "slug": "_2-query传参"
        },
        {
          "level": 3,
          "title": "3 动态路径传参",
          "slug": "_3-动态路径传参"
        },
        {
          "level": 2,
          "title": "鸡汤时刻",
          "slug": "鸡汤时刻"
        }
      ],
      "excerpt": "<h2 id=\"前奏\"><a class=\"header-anchor\" href=\"#前奏\">#</a> 前奏</h2>\n<div class=\"custom-block tip\"><p class=\"title\"></p><p>这是一篇关于在Vue项目中路由传参的文章o(<strong>￣︶￣</strong>)o</p>\n</div>",
      "lastUpdated": "1/19/2022, 4:27:50 PM"
    },
    {
      "title": "让我的Vue得到重生(三)-与vuex来一次邂逅",
      "frontmatter": {
        "title": "让我的Vue得到重生(三)-与vuex来一次邂逅",
        "date": "2022-01-19T00:00:00.000Z",
        "tags": [
          "Vue"
        ],
        "categories": [
          "Vue"
        ]
      },
      "regularPath": "/blogs/category/Vue/vuex.html",
      "relativePath": "blogs/category/Vue/vuex.md",
      "key": "v-71d07c7b",
      "path": "/blogs/category/Vue/vuex.html",
      "headers": [
        {
          "level": 2,
          "title": "前奏",
          "slug": "前奏"
        },
        {
          "level": 2,
          "title": "主题",
          "slug": "主题"
        },
        {
          "level": 2,
          "title": "State",
          "slug": "state"
        },
        {
          "level": 3,
          "title": "1.mapState辅助函数",
          "slug": "_1-mapstate辅助函数"
        }
      ],
      "excerpt": "<div class=\"custom-block tip\"><p class=\"title\"></p><p>最是人间留不住，朱辞颜镜花辞树，与vuex来一次完美的邂逅吧!o(<strong>￣︶￣</strong>)o</p>\n</div>"
    },
    {
      "title": "留言板",
      "frontmatter": {
        "title": "留言板",
        "date": "2022-01-05T00:00:00.000Z"
      },
      "regularPath": "/messageBoard.html",
      "relativePath": "messageBoard.md",
      "key": "v-e5172948",
      "path": "/messageBoard.html"
    },
    {
      "title": "我的个人简介",
      "frontmatter": {
        "title": "我的个人简介",
        "date": "2022-01-14T00:00:00.000Z",
        "author": "夏鸣予",
        "tags": [
          "introduce"
        ],
        "sticky": 1
      },
      "regularPath": "/blogs/introduce/introduce.html",
      "relativePath": "blogs/introduce/introduce.md",
      "key": "v-8cfa1d18",
      "path": "/blogs/introduce/introduce.html",
      "headers": [
        {
          "level": 2,
          "title": "个人经历与简介",
          "slug": "个人经历与简介"
        },
        {
          "level": 2,
          "title": "爱好",
          "slug": "爱好"
        },
        {
          "level": 2,
          "title": "结束语",
          "slug": "结束语"
        }
      ],
      "excerpt": "<div class=\"custom-block tip\"><p class=\"title\"></p><p>赏脸看看作者的个人简介把(￣︶￣)&gt;</p>\n</div>",
      "lastUpdated": "1/19/2022, 4:27:50 PM"
    },
    {
      "title": "git常用命令",
      "frontmatter": {
        "title": "git常用命令",
        "date": "2022-01-14T00:00:00.000Z",
        "tags": [
          "git"
        ],
        "categories": [
          "Git"
        ],
        "sticky": 2
      },
      "regularPath": "/blogs/category/git/gitcmd.html",
      "relativePath": "blogs/category/git/gitcmd.md",
      "key": "v-d084738a",
      "path": "/blogs/category/git/gitcmd.html",
      "headers": [
        {
          "level": 3,
          "title": "提交本地仓库",
          "slug": "提交本地仓库"
        },
        {
          "level": 3,
          "title": "关联远程仓库",
          "slug": "关联远程仓库"
        },
        {
          "level": 3,
          "title": "推送到远程仓库,第一次推送要写远程分支的名字,推送成功后,后面直接git push就行了",
          "slug": "推送到远程仓库-第一次推送要写远程分支的名字-推送成功后-后面直接git-push就行了"
        },
        {
          "level": 3,
          "title": "查看远程仓库地址",
          "slug": "查看远程仓库地址"
        },
        {
          "level": 3,
          "title": "撤销本次git add .",
          "slug": "撤销本次git-add"
        },
        {
          "level": 3,
          "title": "撤销本次git commit不撤销add",
          "slug": "撤销本次git-commit不撤销add"
        },
        {
          "level": 3,
          "title": "git 移除",
          "slug": "git-移除"
        },
        {
          "level": 3,
          "title": "git 创建分支",
          "slug": "git-创建分支"
        },
        {
          "level": 3,
          "title": "git 查看当前分支",
          "slug": "git-查看当前分支"
        },
        {
          "level": 3,
          "title": "git 查看历史提交记录",
          "slug": "git-查看历史提交记录"
        },
        {
          "level": 3,
          "title": "git 克隆项目",
          "slug": "git-克隆项目"
        },
        {
          "level": 3,
          "title": "git 回到指定版本",
          "slug": "git-回到指定版本"
        },
        {
          "level": 3,
          "title": "下班之前你需要做的事情",
          "slug": "下班之前你需要做的事情"
        },
        {
          "level": 2,
          "title": "遇到的一些问题",
          "slug": "遇到的一些问题"
        },
        {
          "level": 2,
          "title": "结束语",
          "slug": "结束语"
        },
        {
          "level": 2,
          "title": "鸡汤时刻",
          "slug": "鸡汤时刻"
        }
      ],
      "excerpt": "<div class=\"custom-block tip\"><p class=\"title\"></p><p>这是一篇关于git常用命令的文档o(￣▽￣)ｄ</p>\n</div>",
      "lastUpdated": "1/19/2022, 4:27:50 PM"
    },
    {
      "frontmatter": {
        "layout": "Tags",
        "title": "Tags"
      },
      "regularPath": "/tag/",
      "key": "v-b1564aac",
      "path": "/tag/"
    },
    {
      "frontmatter": {
        "layout": "FrontmatterKey",
        "title": "Categories"
      },
      "regularPath": "/categories/",
      "key": "v-ef9325c4",
      "path": "/categories/"
    },
    {
      "frontmatter": {
        "layout": "TimeLines",
        "title": "Timeline"
      },
      "regularPath": "/timeline/",
      "key": "v-6319eb4e",
      "path": "/timeline/"
    },
    {
      "frontmatter": {
        "layout": "Tag",
        "title": "ES6 Tags"
      },
      "regularPath": "/tag/ES6/",
      "key": "v-3257dcde",
      "path": "/tag/ES6/"
    },
    {
      "frontmatter": {
        "layout": "Tag",
        "title": "JavaScript Tags"
      },
      "regularPath": "/tag/JavaScript/",
      "key": "v-7a5f6990",
      "path": "/tag/JavaScript/"
    },
    {
      "frontmatter": {
        "layout": "Tag",
        "title": "Vue Tags"
      },
      "regularPath": "/tag/Vue/",
      "key": "v-32475d9a",
      "path": "/tag/Vue/"
    },
    {
      "frontmatter": {
        "layout": "Tag",
        "title": "introduce Tags"
      },
      "regularPath": "/tag/introduce/",
      "key": "v-79a2a91a",
      "path": "/tag/introduce/"
    },
    {
      "frontmatter": {
        "layout": "Tag",
        "title": "git Tags"
      },
      "regularPath": "/tag/git/",
      "key": "v-32383f72",
      "path": "/tag/git/"
    },
    {
      "frontmatter": {
        "layout": "Category",
        "title": "ES6 Categories"
      },
      "regularPath": "/categories/ES6/",
      "key": "v-7eff4a05",
      "path": "/categories/ES6/"
    },
    {
      "frontmatter": {
        "layout": "Category",
        "title": "Vue Categories"
      },
      "regularPath": "/categories/Vue/",
      "key": "v-7f0789a7",
      "path": "/categories/Vue/"
    },
    {
      "frontmatter": {
        "layout": "Category",
        "title": "Git Categories"
      },
      "regularPath": "/categories/Git/",
      "key": "v-7f008cdb",
      "path": "/categories/Git/"
    }
  ],
  "themeConfig": {
    "author": "夏鸣予",
    "huawei": true,
    "nav": [
      {
        "text": "首页",
        "link": "/",
        "icon": "reco-home"
      },
      {
        "text": "时间轴",
        "link": "/timeline/",
        "icon": "reco-date"
      },
      {
        "text": "留言板",
        "icon": "reco-message",
        "link": "/messageBoard"
      },
      {
        "text": "Contact",
        "icon": "reco-message",
        "items": [
          {
            "text": "gitee",
            "link": "https://gitee.com/smart-x"
          }
        ]
      }
    ],
    "valineConfig": {
      "appId": "3LHlTn3FClOQQwfLAMUuucTc-gzGzoHsz",
      "appKey": "xp6lSBicUhJOY3LLQIEPIYEv"
    },
    "sidebar": {
      "/docs/theme-reco/": [
        "",
        "theme",
        "plugin",
        "api"
      ]
    },
    "type": "blog",
    "blogConfig": {
      "category": {
        "location": 2,
        "text": "知识"
      },
      "tag": {
        "location": 3,
        "text": "标签"
      }
    },
    "friendLink": [
      {
        "title": "午后南杂",
        "desc": "Enjoy when you can, and endure when you must.",
        "email": "1156743527@qq.com",
        "link": "https://www.recoluan.com"
      },
      {
        "title": "vuepress-theme-reco",
        "desc": "A simple and beautiful vuepress Blog & Doc theme.",
        "avatar": "https://vuepress-theme-reco.recoluan.com/icon_vuepress_reco.png",
        "link": "https://vuepress-theme-reco.recoluan.com"
      }
    ],
    "logo": "/logo.png",
    "search": true,
    "searchMaxSuggestions": 10,
    "lastUpdated": "Last Updated",
    "authorAvatar": "/avatar.png",
    "record": "xxxx",
    "startYear": "2017"
  }
}