/**
 * Generated by "@vuepress/internal-site-data"
 */
export const siteData = {
  "title": "生活笔记XY",
  "description": "永远怀着一刻真诚与善良的心",
  "base": "/",
  "headTags": [
    [
      "link",
      {
        "rel": "icon",
        "href": "/favicon.ico"
      }
    ],
    [
      "meta",
      {
        "name": "viewport",
        "content": "width=device-width,initial-scale=1,user-scalable=no"
      }
    ]
  ],
  "pages": [
    {
      "title": "Home",
      "frontmatter": {
        "home": true,
        "heroText": "夏鸣予",
        "tagline": "不要因为没有掌声,而丢掉梦想。",
        "bgImageStyle": {
          "height": "450px"
        },
        "isShowTitleInHome": false,
        "actionText": "Guide",
        "actionLink": "/views/other/guide",
        "features": [
          {
            "title": "Yesterday",
            "details": "开发一款看着开心、写着顺手的 vuepress 博客主题"
          },
          {
            "title": "Today",
            "details": "希望帮助更多的人花更多的时间在内容创作上，而不是博客搭建上"
          },
          {
            "title": "Tomorrow",
            "details": "希望更多的爱好者能够参与进来，帮助这个主题更好的成长"
          }
        ]
      },
      "regularPath": "/",
      "relativePath": "README.md",
      "key": "v-f1694f66",
      "path": "/",
      "lastUpdated": "2/15/2022, 9:23:03 PM"
    },
    {
      "title": "ES6学习之路(七) 类",
      "frontmatter": {
        "title": "ES6学习之路(七) 类",
        "date": "2022-02-21T00:00:00.000Z",
        "tags": [
          "js"
        ],
        "categories": [
          "ES6"
        ]
      },
      "regularPath": "/blogs/category/ES6/class.html",
      "relativePath": "blogs/category/ES6/class.md",
      "key": "v-6d1ffaaa",
      "path": "/blogs/category/ES6/class.html",
      "headers": [
        {
          "level": 2,
          "title": "前言",
          "slug": "前言"
        },
        {
          "level": 2,
          "title": "老版新版对比",
          "slug": "老版新版对比"
        },
        {
          "level": 2,
          "title": "类的方法",
          "slug": "类的方法"
        },
        {
          "level": 2,
          "title": "遍历问题",
          "slug": "遍历问题"
        },
        {
          "level": 2,
          "title": "类里面的constructor方法",
          "slug": "类里面的constructor方法"
        },
        {
          "level": 2,
          "title": "类的实例",
          "slug": "类的实例"
        },
        {
          "level": 2,
          "title": "好文推荐",
          "slug": "好文推荐"
        },
        {
          "level": 2,
          "title": "取值函数(get)与存值函数(set)",
          "slug": "取值函数-get-与存值函数-set"
        },
        {
          "level": 2,
          "title": "属性表达式",
          "slug": "属性表达式"
        },
        {
          "level": 2,
          "title": "name属性",
          "slug": "name属性"
        },
        {
          "level": 2,
          "title": "静态方法",
          "slug": "静态方法"
        },
        {
          "level": 2,
          "title": "new.target",
          "slug": "new-target"
        },
        {
          "level": 2,
          "title": "参考文档",
          "slug": "参考文档"
        },
        {
          "level": 2,
          "title": "博客",
          "slug": "博客"
        }
      ],
      "lastUpdated": "2/22/2022, 9:27:56 PM"
    },
    {
      "title": "ES6学习之路(八) 类的继承",
      "frontmatter": {
        "title": "ES6学习之路(八) 类的继承",
        "date": "2022-02-22T00:00:00.000Z",
        "tags": [
          "js"
        ],
        "categories": [
          "ES6"
        ]
      },
      "regularPath": "/blogs/category/ES6/classExtend.html",
      "relativePath": "blogs/category/ES6/classExtend.md",
      "key": "v-282efa37",
      "path": "/blogs/category/ES6/classExtend.html",
      "headers": [
        {
          "level": 2,
          "title": "简介",
          "slug": "简介"
        },
        {
          "level": 2,
          "title": "继承原则",
          "slug": "继承原则"
        },
        {
          "level": 2,
          "title": "获取父类是谁",
          "slug": "获取父类是谁"
        },
        {
          "level": 2,
          "title": "Super关键字",
          "slug": "super关键字"
        },
        {
          "level": 3,
          "title": "1.化身为函数",
          "slug": "_1-化身为函数"
        },
        {
          "level": 3,
          "title": "2.化身为对象",
          "slug": "_2-化身为对象"
        },
        {
          "level": 3,
          "title": "3.注意点",
          "slug": "_3-注意点"
        },
        {
          "level": 2,
          "title": "博客",
          "slug": "博客"
        },
        {
          "level": 2,
          "title": "结束语",
          "slug": "结束语"
        }
      ],
      "lastUpdated": "2/22/2022, 9:27:56 PM"
    },
    {
      "title": "ES6学习之路(一) Generator函数",
      "frontmatter": {
        "title": "ES6学习之路(一) Generator函数",
        "date": "2022-01-5",
        "tags": [
          "ES6",
          "JavaScript"
        ],
        "categories": [
          "ES6"
        ]
      },
      "regularPath": "/blogs/category/ES6/generator.html",
      "relativePath": "blogs/category/ES6/generator.md",
      "key": "v-b413a096",
      "path": "/blogs/category/ES6/generator.html",
      "headers": [
        {
          "level": 2,
          "title": "前奏",
          "slug": "前奏"
        },
        {
          "level": 2,
          "title": "主题",
          "slug": "主题"
        },
        {
          "level": 3,
          "title": "主角",
          "slug": "主角"
        },
        {
          "level": 3,
          "title": "next函数传参",
          "slug": "next函数传参"
        }
      ],
      "excerpt": "<div class=\"custom-block tip\"><p class=\"title\"></p><p>这是一篇关于ES6generator函数的知识o(￣▽￣)ｄ</p>\n</div>",
      "lastUpdated": "1/24/2022, 10:21:23 PM"
    },
    {
      "title": "ES6学习之路(三) 解构赋值",
      "frontmatter": {
        "title": "ES6学习之路(三) 解构赋值",
        "date": "2022-02-10T00:00:00.000Z",
        "tags": [
          "js"
        ],
        "categories": [
          "ES6"
        ]
      },
      "regularPath": "/blogs/category/ES6/deconstructionAssignment.html",
      "relativePath": "blogs/category/ES6/deconstructionAssignment.md",
      "key": "v-c324f84a",
      "path": "/blogs/category/ES6/deconstructionAssignment.html",
      "headers": [
        {
          "level": 2,
          "title": "数组的解构赋值",
          "slug": "数组的解构赋值"
        },
        {
          "level": 3,
          "title": "解构不成功",
          "slug": "解构不成功"
        },
        {
          "level": 3,
          "title": "部分解构",
          "slug": "部分解构"
        },
        {
          "level": 3,
          "title": "默认值",
          "slug": "默认值"
        },
        {
          "level": 2,
          "title": "对象的解构赋值",
          "slug": "对象的解构赋值"
        },
        {
          "level": 3,
          "title": "解构赋值重命名",
          "slug": "解构赋值重命名"
        },
        {
          "level": 3,
          "title": "解构失败",
          "slug": "解构失败"
        },
        {
          "level": 2,
          "title": "字符串的解构赋值",
          "slug": "字符串的解构赋值"
        },
        {
          "level": 2,
          "title": "数值和布尔值的解构赋值",
          "slug": "数值和布尔值的解构赋值"
        },
        {
          "level": 2,
          "title": "函数参数的解构赋值",
          "slug": "函数参数的解构赋值"
        },
        {
          "level": 2,
          "title": "用途",
          "slug": "用途"
        },
        {
          "level": 3,
          "title": "交换变量的值",
          "slug": "交换变量的值"
        },
        {
          "level": 3,
          "title": "从函数中返回多个值",
          "slug": "从函数中返回多个值"
        },
        {
          "level": 3,
          "title": "函数调用时直接解构",
          "slug": "函数调用时直接解构"
        },
        {
          "level": 2,
          "title": "我在vue项目中的基操",
          "slug": "我在vue项目中的基操"
        },
        {
          "level": 3,
          "title": "解构路由对象中的query和params参数",
          "slug": "解构路由对象中的query和params参数"
        },
        {
          "level": 3,
          "title": "axios网络请求中解构data",
          "slug": "axios网络请求中解构data"
        }
      ],
      "excerpt": "",
      "lastUpdated": "2/10/2022, 9:33:49 PM"
    },
    {
      "title": "ES6学习之路(九)-Promise",
      "frontmatter": {
        "title": "ES6学习之路(九)-Promise",
        "date": "2022-02-22T00:00:00.000Z",
        "tags": [
          "js"
        ],
        "categories": [
          "ES6"
        ]
      },
      "regularPath": "/blogs/category/ES6/promise.html",
      "relativePath": "blogs/category/ES6/promise.md",
      "key": "v-7b327136",
      "path": "/blogs/category/ES6/promise.html",
      "headers": [
        {
          "level": 2,
          "title": "使用Promise封装函数",
          "slug": "使用promise封装函数"
        },
        {
          "level": 2,
          "title": "使用Promise.all发送并发请求",
          "slug": "使用promise-all发送并发请求"
        },
        {
          "level": 2,
          "title": "Promise.race获取最先返回的值",
          "slug": "promise-race获取最先返回的值"
        },
        {
          "level": 2,
          "title": "Promise.allSettled请求完成继续下一步",
          "slug": "promise-allsettled请求完成继续下一步"
        },
        {
          "level": 2,
          "title": "总结",
          "slug": "总结"
        }
      ],
      "lastUpdated": "2/22/2022, 9:27:56 PM"
    },
    {
      "title": "ES6学习之路(二) let&const",
      "frontmatter": {
        "title": "ES6学习之路(二) let&const",
        "date": "2022-02-10T00:00:00.000Z",
        "tags": [
          "ES6",
          "JavaScript"
        ],
        "categories": [
          "ES6"
        ]
      },
      "regularPath": "/blogs/category/ES6/letconst.html",
      "relativePath": "blogs/category/ES6/letconst.md",
      "key": "v-cb115a0a",
      "path": "/blogs/category/ES6/letconst.html",
      "headers": [
        {
          "level": 2,
          "title": "let",
          "slug": "let"
        },
        {
          "level": 3,
          "title": "let声明的变量存在块级作用域",
          "slug": "let声明的变量存在块级作用域"
        },
        {
          "level": 3,
          "title": "不允许重复声明变量",
          "slug": "不允许重复声明变量"
        },
        {
          "level": 3,
          "title": "for循环与let",
          "slug": "for循环与let"
        },
        {
          "level": 3,
          "title": "不存在变量提升",
          "slug": "不存在变量提升"
        },
        {
          "level": 3,
          "title": "暂存性死区",
          "slug": "暂存性死区"
        },
        {
          "level": 3,
          "title": "有趣的知识",
          "slug": "有趣的知识"
        },
        {
          "level": 3,
          "title": "杂项",
          "slug": "杂项"
        },
        {
          "level": 2,
          "title": "const",
          "slug": "const"
        },
        {
          "level": 2,
          "title": "顶层对象",
          "slug": "顶层对象"
        }
      ],
      "lastUpdated": "2/10/2022, 9:33:49 PM"
    },
    {
      "title": "ES6学习之路(四) 运算符的扩展",
      "frontmatter": {
        "title": "ES6学习之路(四) 运算符的扩展",
        "date": "2022-02-10T00:00:00.000Z",
        "tags": [
          "ES6",
          "JavaScript"
        ],
        "categories": [
          "ES6"
        ]
      },
      "regularPath": "/blogs/category/ES6/operator.html",
      "relativePath": "blogs/category/ES6/operator.md",
      "key": "v-04e1f27b",
      "path": "/blogs/category/ES6/operator.html",
      "headers": [
        {
          "level": 2,
          "title": "指数运算符",
          "slug": "指数运算符"
        },
        {
          "level": 2,
          "title": "链判断运算符",
          "slug": "链判断运算符"
        },
        {
          "level": 3,
          "title": "运行函数",
          "slug": "运行函数"
        },
        {
          "level": 2,
          "title": "短路机制",
          "slug": "短路机制"
        },
        {
          "level": 2,
          "title": "NULL判断运算符",
          "slug": "null判断运算符"
        },
        {
          "level": 3,
          "title": "经典的设置默认值方法",
          "slug": "经典的设置默认值方法"
        }
      ],
      "lastUpdated": "2/10/2022, 9:33:49 PM"
    },
    {
      "title": "ES6学习之路(六) Set&Map数据结构",
      "frontmatter": {
        "title": "ES6学习之路(六) Set&Map数据结构",
        "date": "2022-02-10T00:00:00.000Z",
        "tags": [
          "js"
        ],
        "categories": [
          "ES6"
        ]
      },
      "regularPath": "/blogs/category/ES6/setMap.html",
      "relativePath": "blogs/category/ES6/setMap.md",
      "key": "v-df4fc68a",
      "path": "/blogs/category/ES6/setMap.html",
      "headers": [
        {
          "level": 2,
          "title": "Set",
          "slug": "set"
        },
        {
          "level": 3,
          "title": "简要介绍",
          "slug": "简要介绍"
        },
        {
          "level": 3,
          "title": "有趣的知识",
          "slug": "有趣的知识"
        },
        {
          "level": 3,
          "title": "Set实例的属性与方法",
          "slug": "set实例的属性与方法"
        },
        {
          "level": 2,
          "title": "WeakSet",
          "slug": "weakset"
        },
        {
          "level": 3,
          "title": "弱引用",
          "slug": "弱引用"
        },
        {
          "level": 2,
          "title": "Map",
          "slug": "map"
        },
        {
          "level": 3,
          "title": "四大操作方法",
          "slug": "四大操作方法-2"
        },
        {
          "level": 3,
          "title": "四大遍历方法",
          "slug": "四大遍历方法-2"
        },
        {
          "level": 3,
          "title": "1.map结构转数组",
          "slug": "_1-map结构转数组"
        },
        {
          "level": 3,
          "title": "2.数组转map",
          "slug": "_2-数组转map"
        },
        {
          "level": 3,
          "title": "3.map转对象",
          "slug": "_3-map转对象"
        },
        {
          "level": 3,
          "title": "4.对象转map",
          "slug": "_4-对象转map"
        },
        {
          "level": 2,
          "title": "WeakMap",
          "slug": "weakmap"
        },
        {
          "level": 2,
          "title": "博客",
          "slug": "博客"
        }
      ],
      "lastUpdated": "2/19/2022, 11:05:19 PM"
    },
    {
      "title": "JS之includes函数",
      "frontmatter": {
        "title": "JS之includes函数",
        "date": "2022-02-13T00:00:00.000Z",
        "tags": [
          "js"
        ],
        "categories": [
          "JavaScript"
        ]
      },
      "regularPath": "/blogs/category/JavaScript/includes.html",
      "relativePath": "blogs/category/JavaScript/includes.md",
      "key": "v-1b44d80e",
      "path": "/blogs/category/JavaScript/includes.html",
      "headers": [
        {
          "level": 3,
          "title": "fromIndex大于等于数组长度直接返回false",
          "slug": "fromindex大于等于数组长度直接返回false"
        },
        {
          "level": 2,
          "title": "类数组对象也是可以调用该方法的",
          "slug": "类数组对象也是可以调用该方法的"
        },
        {
          "level": 2,
          "title": "总结",
          "slug": "总结"
        }
      ],
      "lastUpdated": "2/15/2022, 9:23:03 PM"
    },
    {
      "title": "ES6学习之路(五) js的Symbol类型",
      "frontmatter": {
        "title": "ES6学习之路(五) js的Symbol类型",
        "date": "2022-02-10T00:00:00.000Z",
        "tags": [
          "js"
        ],
        "categories": [
          "ES6"
        ]
      },
      "regularPath": "/blogs/category/ES6/symbol.html",
      "relativePath": "blogs/category/ES6/symbol.md",
      "key": "v-6319ebfb",
      "path": "/blogs/category/ES6/symbol.html",
      "headers": [
        {
          "level": 2,
          "title": "简介",
          "slug": "简介"
        },
        {
          "level": 2,
          "title": "获取Symbol的描述",
          "slug": "获取symbol的描述"
        },
        {
          "level": 2,
          "title": "消除魔术字符串",
          "slug": "消除魔术字符串"
        },
        {
          "level": 2,
          "title": "Object.getOwnPropertySymbols()方法获取symbol属性数组",
          "slug": "object-getownpropertysymbols-方法获取symbol属性数组"
        },
        {
          "level": 2,
          "title": "感慨时间",
          "slug": "感慨时间"
        },
        {
          "level": 2,
          "title": "Symbol.for(), Symbol.keyfor()方法",
          "slug": "symbol-for-symbol-keyfor-方法"
        },
        {
          "level": 3,
          "title": "Symbol.for()",
          "slug": "symbol-for"
        },
        {
          "level": 3,
          "title": "Symbol.keyfor()",
          "slug": "symbol-keyfor"
        },
        {
          "level": 2,
          "title": "内置的Symbol值",
          "slug": "内置的symbol值"
        },
        {
          "level": 3,
          "title": "1.Symbol.hasInstance",
          "slug": "_1-symbol-hasinstance"
        },
        {
          "level": 3,
          "title": "2.Symbol.isConcatSpreadable",
          "slug": "_2-symbol-isconcatspreadable"
        }
      ],
      "lastUpdated": "2/14/2022, 9:57:12 PM"
    },
    {
      "title": "JS之concat函数",
      "frontmatter": {
        "title": "JS之concat函数",
        "date": "2022-02-13T00:00:00.000Z",
        "tags": [
          "js"
        ],
        "categories": [
          "JavaScript"
        ]
      },
      "regularPath": "/blogs/category/JavaScript/concat.html",
      "relativePath": "blogs/category/JavaScript/concat.md",
      "key": "v-46ad39a7",
      "path": "/blogs/category/JavaScript/concat.html",
      "headers": [
        {
          "level": 2,
          "title": "数组的concat方法",
          "slug": "数组的concat方法"
        },
        {
          "level": 3,
          "title": "1.连接2个数组",
          "slug": "_1-连接2个数组"
        },
        {
          "level": 3,
          "title": "2.连接3个数组",
          "slug": "_2-连接3个数组"
        },
        {
          "level": 3,
          "title": "3.连接值到数组",
          "slug": "_3-连接值到数组"
        },
        {
          "level": 3,
          "title": "有趣的知识",
          "slug": "有趣的知识"
        },
        {
          "level": 3,
          "title": "Symbol.isConcatSpreadable",
          "slug": "symbol-isconcatspreadable"
        },
        {
          "level": 2,
          "title": "字符串的concat方法",
          "slug": "字符串的concat方法"
        }
      ],
      "lastUpdated": "2/15/2022, 9:23:03 PM"
    },
    {
      "title": "JS之reduce函数",
      "frontmatter": {
        "title": "JS之reduce函数",
        "date": "2022-01-14T00:00:00.000Z",
        "tags": [
          "js"
        ],
        "categories": [
          "JavaScript"
        ]
      },
      "regularPath": "/blogs/category/JavaScript/reduce.html",
      "relativePath": "blogs/category/JavaScript/reduce.md",
      "key": "v-1c09b6fa",
      "path": "/blogs/category/JavaScript/reduce.html",
      "headers": [
        {
          "level": 2,
          "title": "用法举例",
          "slug": "用法举例"
        },
        {
          "level": 3,
          "title": "1.求数组的和",
          "slug": "_1-求数组的和"
        },
        {
          "level": 3,
          "title": "2.累加对象数组里面的值",
          "slug": "_2-累加对象数组里面的值"
        },
        {
          "level": 3,
          "title": "3.二维数组转一维",
          "slug": "_3-二维数组转一维"
        },
        {
          "level": 3,
          "title": "4.计算数组中每个元素出现的次数",
          "slug": "_4-计算数组中每个元素出现的次数"
        },
        {
          "level": 3,
          "title": "5.按属性分类",
          "slug": "_5-按属性分类"
        },
        {
          "level": 3,
          "title": "6. 把对象数组中的数组合并起来",
          "slug": "_6-把对象数组中的数组合并起来"
        },
        {
          "level": 3,
          "title": "7.数组去重",
          "slug": "_7-数组去重"
        },
        {
          "level": 3,
          "title": "8.按顺序运行Promise",
          "slug": "_8-按顺序运行promise"
        },
        {
          "level": 2,
          "title": "博客",
          "slug": "博客"
        }
      ],
      "excerpt": "<div class=\"custom-block tip\"><p class=\"title\"></p><p>这是一篇关于js reduce函数的文档o(￣▽￣)ｄ</p>\n</div>",
      "lastUpdated": "2/8/2022, 11:10:03 AM"
    },
    {
      "title": "JS之splice和slice函数",
      "frontmatter": {
        "title": "JS之splice和slice函数",
        "date": "2022-02-07T00:00:00.000Z",
        "tags": [
          "js"
        ],
        "categories": [
          "JavaScript"
        ]
      },
      "regularPath": "/blogs/category/JavaScript/spliceSlice.html",
      "relativePath": "blogs/category/JavaScript/spliceSlice.md",
      "key": "v-543a3abe",
      "path": "/blogs/category/JavaScript/spliceSlice.html",
      "headers": [
        {
          "level": 2,
          "title": "Splice",
          "slug": "splice"
        },
        {
          "level": 2,
          "title": "示例",
          "slug": "示例"
        },
        {
          "level": 3,
          "title": "示例1",
          "slug": "示例1"
        },
        {
          "level": 3,
          "title": "示例2",
          "slug": "示例2"
        },
        {
          "level": 3,
          "title": "示例3",
          "slug": "示例3"
        },
        {
          "level": 3,
          "title": "示例4",
          "slug": "示例4"
        },
        {
          "level": 3,
          "title": "示例5",
          "slug": "示例5"
        },
        {
          "level": 2,
          "title": "Slice",
          "slug": "slice"
        },
        {
          "level": 3,
          "title": "示例",
          "slug": "示例-2"
        },
        {
          "level": 2,
          "title": "tip",
          "slug": "tip"
        }
      ],
      "excerpt": "<div class=\"custom-block tip\"><p class=\"title\"></p><p>这是一篇关于js Splice和slice函数的文档o(￣▽￣)ｄ</p>\n</div>",
      "lastUpdated": "2/8/2022, 11:10:03 AM"
    },
    {
      "title": "JS之split和join函数",
      "frontmatter": {
        "title": "JS之split和join函数",
        "date": "2022-02-015",
        "tags": [
          "js"
        ],
        "categories": [
          "JavaScript"
        ]
      },
      "regularPath": "/blogs/category/JavaScript/splitJoin.html",
      "relativePath": "blogs/category/JavaScript/splitJoin.md",
      "key": "v-34331cbe",
      "path": "/blogs/category/JavaScript/splitJoin.html",
      "headers": [
        {
          "level": 2,
          "title": "Join方法",
          "slug": "join方法"
        },
        {
          "level": 3,
          "title": "示例",
          "slug": "示例"
        },
        {
          "level": 3,
          "title": "连接类数组对象",
          "slug": "连接类数组对象"
        },
        {
          "level": 2,
          "title": "Split",
          "slug": "split"
        },
        {
          "level": 2,
          "title": "示例",
          "slug": "示例-2"
        },
        {
          "level": 3,
          "title": "结束语",
          "slug": "结束语"
        }
      ],
      "lastUpdated": "2/15/2022, 9:23:03 PM"
    },
    {
      "title": "原生js实现放大镜效果",
      "frontmatter": {
        "title": "原生js实现放大镜效果",
        "date": "2022-02-20T00:00:00.000Z",
        "tags": [
          "js"
        ],
        "categories": [
          "JavaScript"
        ]
      },
      "regularPath": "/blogs/category/JavaScript/zoom.html",
      "relativePath": "blogs/category/JavaScript/zoom.md",
      "key": "v-0a05322e",
      "path": "/blogs/category/JavaScript/zoom.html",
      "headers": [
        {
          "level": 2,
          "title": "效果图",
          "slug": "效果图"
        },
        {
          "level": 2,
          "title": "设计思路",
          "slug": "设计思路"
        },
        {
          "level": 3,
          "title": "基本架子",
          "slug": "基本架子"
        },
        {
          "level": 3,
          "title": "蒙版",
          "slug": "蒙版"
        },
        {
          "level": 3,
          "title": "放大效果图",
          "slug": "放大效果图"
        },
        {
          "level": 2,
          "title": "逻辑设计",
          "slug": "逻辑设计"
        },
        {
          "level": 3,
          "title": "蒙版跟放大的图肯定要先隐藏",
          "slug": "蒙版跟放大的图肯定要先隐藏"
        },
        {
          "level": 3,
          "title": "鼠标移入图片显示蒙版",
          "slug": "鼠标移入图片显示蒙版"
        },
        {
          "level": 3,
          "title": "鼠标移动蒙版跟着移动",
          "slug": "鼠标移动蒙版跟着移动"
        },
        {
          "level": 2,
          "title": "处理边界情况",
          "slug": "处理边界情况"
        },
        {
          "level": 2,
          "title": "大图移动",
          "slug": "大图移动"
        },
        {
          "level": 2,
          "title": "小优化",
          "slug": "小优化"
        },
        {
          "level": 2,
          "title": "终版",
          "slug": "终版"
        }
      ],
      "lastUpdated": "2/20/2022, 9:42:22 PM"
    },
    {
      "title": "removeListener移除事件报错",
      "frontmatter": {
        "title": "removeListener移除事件报错",
        "date": "2022-02-22T00:00:00.000Z",
        "tags": [
          "js"
        ],
        "categories": [
          "JavaScript"
        ]
      },
      "regularPath": "/blogs/category/JavaScript/removeListener.html",
      "relativePath": "blogs/category/JavaScript/removeListener.md",
      "key": "v-87e791c2",
      "path": "/blogs/category/JavaScript/removeListener.html",
      "headers": [
        {
          "level": 2,
          "title": "问题描述",
          "slug": "问题描述"
        },
        {
          "level": 2,
          "title": "解决方案",
          "slug": "解决方案"
        }
      ],
      "lastUpdated": "2/22/2022, 9:27:56 PM"
    },
    {
      "title": "Vue中使用normalize.css",
      "frontmatter": {
        "title": "Vue中使用normalize.css",
        "date": "2022-02-08T00:00:00.000Z",
        "tags": [
          "Vue"
        ],
        "categories": [
          "Vue"
        ]
      },
      "regularPath": "/blogs/category/Vue/normalize.html",
      "relativePath": "blogs/category/Vue/normalize.md",
      "key": "v-62f1a805",
      "path": "/blogs/category/Vue/normalize.html",
      "headers": [
        {
          "level": 2,
          "title": "主题",
          "slug": "主题"
        }
      ],
      "lastUpdated": "2/9/2022, 10:17:27 AM"
    },
    {
      "title": "恶补js基础第一天",
      "frontmatter": {
        "title": "恶补js基础第一天",
        "date": "2022-02-23T00:00:00.000Z",
        "tags": [
          "js"
        ],
        "categories": [
          "JavaScript"
        ]
      },
      "regularPath": "/blogs/category/JavaScript/jsStudyDay1.html",
      "relativePath": "blogs/category/JavaScript/jsStudyDay1.md",
      "key": "v-12396bc1",
      "path": "/blogs/category/JavaScript/jsStudyDay1.html",
      "headers": [
        {
          "level": 2,
          "title": "变量提升(hoisting)",
          "slug": "变量提升-hoisting"
        },
        {
          "level": 2,
          "title": "标识符",
          "slug": "标识符"
        },
        {
          "level": 2,
          "title": "区块",
          "slug": "区块"
        },
        {
          "level": 2,
          "title": "数据类型",
          "slug": "数据类型"
        },
        {
          "level": 2,
          "title": "typeof 运算符",
          "slug": "typeof-运算符"
        },
        {
          "level": 2,
          "title": "谈谈我对null和undefined的理解",
          "slug": "谈谈我对null和undefined的理解"
        },
        {
          "level": 2,
          "title": "布尔值",
          "slug": "布尔值"
        },
        {
          "level": 2,
          "title": "数值范围",
          "slug": "数值范围"
        },
        {
          "level": 2,
          "title": "NAN",
          "slug": "nan"
        },
        {
          "level": 2,
          "title": "IsNaN方法",
          "slug": "isnan方法"
        },
        {
          "level": 2,
          "title": "字符串与数组",
          "slug": "字符串与数组"
        },
        {
          "level": 3,
          "title": "length属性",
          "slug": "length属性"
        },
        {
          "level": 2,
          "title": "对象",
          "slug": "对象"
        },
        {
          "level": 3,
          "title": "取值",
          "slug": "取值"
        },
        {
          "level": 3,
          "title": "in操作符",
          "slug": "in操作符"
        },
        {
          "level": 2,
          "title": "delete操作符",
          "slug": "delete操作符"
        },
        {
          "level": 3,
          "title": "for in",
          "slug": "for-in"
        }
      ]
    },
    {
      "title": "手写分页器组件",
      "frontmatter": {
        "title": "手写分页器组件",
        "date": "2022-02-13T00:00:00.000Z",
        "tags": [
          "Vue"
        ],
        "categories": [
          "Vue"
        ]
      },
      "regularPath": "/blogs/category/Vue/pagenation.html",
      "relativePath": "blogs/category/Vue/pagenation.md",
      "key": "v-62e5d1fb",
      "path": "/blogs/category/Vue/pagenation.html",
      "headers": [
        {
          "level": 2,
          "title": "主题",
          "slug": "主题"
        },
        {
          "level": 2,
          "title": "参数设计",
          "slug": "参数设计"
        },
        {
          "level": 2,
          "title": "处理边界情况",
          "slug": "处理边界情况"
        },
        {
          "level": 3,
          "title": "1.当前页码问题",
          "slug": "_1-当前页码问题"
        },
        {
          "level": 2,
          "title": "循环遍历中间那一坨按钮",
          "slug": "循环遍历中间那一坨按钮"
        },
        {
          "level": 2,
          "title": "边界情况的再处理",
          "slug": "边界情况的再处理"
        },
        {
          "level": 3,
          "title": "1.左边的边界情况",
          "slug": "_1-左边的边界情况"
        },
        {
          "level": 3,
          "title": "2.右边的边界情况处理",
          "slug": "_2-右边的边界情况处理"
        },
        {
          "level": 3,
          "title": "3.上一页下一页按钮的禁用",
          "slug": "_3-上一页下一页按钮的禁用"
        },
        {
          "level": 2,
          "title": "点击事件的绑定",
          "slug": "点击事件的绑定"
        },
        {
          "level": 3,
          "title": "按钮的事件绑定",
          "slug": "按钮的事件绑定"
        },
        {
          "level": 2,
          "title": "激活样式绑定",
          "slug": "激活样式绑定"
        },
        {
          "level": 2,
          "title": "代码优化",
          "slug": "代码优化"
        },
        {
          "level": 2,
          "title": "完整组件代码",
          "slug": "完整组件代码"
        },
        {
          "level": 2,
          "title": "总结",
          "slug": "总结"
        },
        {
          "level": 2,
          "title": "博客",
          "slug": "博客"
        }
      ],
      "lastUpdated": "2/14/2022, 9:57:12 PM"
    },
    {
      "title": "Vue路由传参",
      "frontmatter": {
        "title": "Vue路由传参",
        "date": "2022-01-07T00:00:00.000Z",
        "tags": [
          "Vue"
        ],
        "categories": [
          "Vue"
        ]
      },
      "regularPath": "/blogs/category/Vue/transferParams.html",
      "relativePath": "blogs/category/Vue/transferParams.md",
      "key": "v-eb3e21ca",
      "path": "/blogs/category/Vue/transferParams.html",
      "headers": [
        {
          "level": 2,
          "title": "前奏",
          "slug": "前奏"
        },
        {
          "level": 2,
          "title": "主题",
          "slug": "主题"
        },
        {
          "level": 2,
          "title": "Params传参",
          "slug": "params传参"
        },
        {
          "level": 2,
          "title": "Query传参",
          "slug": "query传参"
        },
        {
          "level": 2,
          "title": "动态路径传参",
          "slug": "动态路径传参"
        },
        {
          "level": 2,
          "title": "Props传参",
          "slug": "props传参"
        },
        {
          "level": 2,
          "title": "Props对象传参",
          "slug": "props对象传参"
        },
        {
          "level": 2,
          "title": "props函数式传参",
          "slug": "props函数式传参"
        },
        {
          "level": 2,
          "title": "小细节",
          "slug": "小细节"
        },
        {
          "level": 2,
          "title": "鸡汤时刻",
          "slug": "鸡汤时刻"
        }
      ],
      "excerpt": "<div class=\"custom-block tip\"><p class=\"title\"></p><p>这是一篇关于在Vue项目中路由传参的文章o(<strong>￣︶￣</strong>)o</p>\n</div>",
      "lastUpdated": "2/8/2022, 11:10:03 AM"
    },
    {
      "title": "Vue进阶-Vue的动态组件",
      "frontmatter": {
        "title": "Vue进阶-Vue的动态组件",
        "date": "2022-01-22T00:00:00.000Z",
        "tags": [
          "Vue"
        ],
        "categories": [
          "Vue"
        ]
      },
      "regularPath": "/blogs/category/Vue/dynamicComponents.html",
      "relativePath": "blogs/category/Vue/dynamicComponents.md",
      "key": "v-9e11ec96",
      "path": "/blogs/category/Vue/dynamicComponents.html",
      "headers": [
        {
          "level": 2,
          "title": "前奏",
          "slug": "前奏"
        },
        {
          "level": 2,
          "title": "主题",
          "slug": "主题"
        },
        {
          "level": 3,
          "title": "解释",
          "slug": "解释"
        },
        {
          "level": 2,
          "title": "使用keep-alive组件缓存部分动态组件",
          "slug": "使用keep-alive组件缓存部分动态组件"
        },
        {
          "level": 2,
          "title": "动态组件传参",
          "slug": "动态组件传参"
        },
        {
          "level": 2,
          "title": "小细节",
          "slug": "小细节"
        },
        {
          "level": 2,
          "title": "哲学时刻",
          "slug": "哲学时刻"
        }
      ],
      "excerpt": "<div class=\"custom-block tip\"><p class=\"title\"></p><p>这是一篇关于在Vue项目使用动态组件的文章o(<strong>￣︶￣</strong>)o</p>\n</div>",
      "lastUpdated": "2/8/2022, 11:10:03 AM"
    },
    {
      "title": "v-if和v-for一起使用",
      "frontmatter": {
        "title": "v-if和v-for一起使用",
        "date": "2022-02-13T00:00:00.000Z",
        "tags": [
          "Vue"
        ],
        "categories": [
          "Vue"
        ]
      },
      "regularPath": "/blogs/category/Vue/vifvfor.html",
      "relativePath": "blogs/category/Vue/vifvfor.md",
      "key": "v-14e0f813",
      "path": "/blogs/category/Vue/vifvfor.html",
      "lastUpdated": "2/14/2022, 9:57:12 PM"
    },
    {
      "title": "在Vue项目中配合Animate.css + transition组件实现动画效果,给你的css加点料(add some water to your css)",
      "frontmatter": {
        "title": "在Vue项目中配合Animate.css + transition组件实现动画效果,给你的css加点料(add some water to your css)",
        "date": "2022-01-24T00:00:00.000Z",
        "tags": [
          "Vue"
        ],
        "categories": [
          "Vue"
        ]
      },
      "regularPath": "/blogs/category/Vue/vueCss.html",
      "relativePath": "blogs/category/Vue/vueCss.md",
      "key": "v-dda97aca",
      "path": "/blogs/category/Vue/vueCss.html",
      "headers": [
        {
          "level": 2,
          "title": "教程",
          "slug": "教程"
        },
        {
          "level": 2,
          "title": "哲学时刻",
          "slug": "哲学时刻"
        }
      ],
      "excerpt": "<div class=\"custom-block tip\"><p class=\"title\"></p><p>v-show + v-if + transition 组件 + Animate.css 给你的css加点料o(￣︶￣)o</p>\n</div>",
      "lastUpdated": "1/24/2022, 10:21:23 PM"
    },
    {
      "title": "Vue项目改变滚动条的样式",
      "frontmatter": {
        "title": "Vue项目改变滚动条的样式",
        "date": "2022-02-25T00:00:00.000Z",
        "tags": [
          "Vue"
        ],
        "categories": [
          "Vue"
        ]
      },
      "regularPath": "/blogs/category/Vue/vuescrollbar.html",
      "relativePath": "blogs/category/Vue/vuescrollbar.md",
      "key": "v-1051298a",
      "path": "/blogs/category/Vue/vuescrollbar.html"
    },
    {
      "title": "Vue进阶-vue的依赖和注入",
      "frontmatter": {
        "title": "Vue进阶-vue的依赖和注入",
        "date": "2022-01-22T00:00:00.000Z",
        "tags": [
          "Vue"
        ],
        "categories": [
          "Vue"
        ]
      },
      "regularPath": "/blogs/category/Vue/pi.html",
      "relativePath": "blogs/category/Vue/pi.md",
      "key": "v-99c196ca",
      "path": "/blogs/category/Vue/pi.html",
      "headers": [
        {
          "level": 2,
          "title": "前奏",
          "slug": "前奏"
        },
        {
          "level": 2,
          "title": "主题",
          "slug": "主题"
        },
        {
          "level": 2,
          "title": "问题",
          "slug": "问题"
        }
      ],
      "excerpt": "<div class=\"custom-block tip\"><p class=\"title\"></p><p>这是一篇关于在Vue项目使用动态组件的文章o(<strong>￣︶￣</strong>)o</p>\n</div>",
      "lastUpdated": "2/8/2022, 11:10:03 AM"
    },
    {
      "title": "axios在Vue项目中的封装",
      "frontmatter": {
        "title": "axios在Vue项目中的封装",
        "date": "2022-01-05T00:00:00.000Z",
        "tags": [
          "axios"
        ],
        "categories": [
          "axios"
        ]
      },
      "regularPath": "/blogs/category/axios/axiospackaging.html",
      "relativePath": "blogs/category/axios/axiospackaging.md",
      "key": "v-13ccba1b",
      "path": "/blogs/category/axios/axiospackaging.html",
      "headers": [
        {
          "level": 2,
          "title": "前言",
          "slug": "前言"
        },
        {
          "level": 2,
          "title": "主题",
          "slug": "主题"
        },
        {
          "level": 2,
          "title": "配置代理",
          "slug": "配置代理"
        },
        {
          "level": 2,
          "title": "环境变量",
          "slug": "环境变量"
        },
        {
          "level": 2,
          "title": "博客",
          "slug": "博客"
        }
      ],
      "lastUpdated": "2/10/2022, 9:33:49 PM"
    },
    {
      "title": "Vue进阶之与vuex来一次邂逅",
      "frontmatter": {
        "title": "Vue进阶之与vuex来一次邂逅",
        "date": "2022-01-19T00:00:00.000Z",
        "tags": [
          "Vue"
        ],
        "categories": [
          "Vue"
        ]
      },
      "regularPath": "/blogs/category/Vue/vuex.html",
      "relativePath": "blogs/category/Vue/vuex.md",
      "key": "v-71d07c7b",
      "path": "/blogs/category/Vue/vuex.html",
      "headers": [
        {
          "level": 2,
          "title": "目录",
          "slug": "目录"
        },
        {
          "level": 2,
          "title": "前奏",
          "slug": "前奏"
        },
        {
          "level": 2,
          "title": "主题",
          "slug": "主题"
        },
        {
          "level": 2,
          "title": "State",
          "slug": "state"
        },
        {
          "level": 3,
          "title": "1.mapState辅助函数",
          "slug": "_1-mapstate辅助函数"
        },
        {
          "level": 2,
          "title": "getters",
          "slug": "getters"
        },
        {
          "level": 3,
          "title": "getters传参",
          "slug": "getters传参"
        },
        {
          "level": 2,
          "title": "Mutations",
          "slug": "mutations"
        },
        {
          "level": 3,
          "title": "关于使用mutations的小细节",
          "slug": "关于使用mutations的小细节"
        },
        {
          "level": 2,
          "title": "Actions",
          "slug": "actions"
        },
        {
          "level": 3,
          "title": "组合Action",
          "slug": "组合action"
        },
        {
          "level": 2,
          "title": "关于伏笔的解释",
          "slug": "关于伏笔的解释"
        },
        {
          "level": 2,
          "title": "Modules",
          "slug": "modules"
        },
        {
          "level": 3,
          "title": "命名空间",
          "slug": "命名空间"
        },
        {
          "level": 3,
          "title": "提示",
          "slug": "提示"
        }
      ],
      "excerpt": "<div class=\"custom-block tip\"><p class=\"title\"></p><p>最是人间留不住，朱辞颜镜花辞树，与vuex来一次完美的邂逅吧!o(<strong>￣︶￣</strong>)o</p>\n</div>",
      "lastUpdated": "2/3/2022, 9:57:18 PM"
    },
    {
      "title": "在markdown中生成目录",
      "frontmatter": {
        "title": "在markdown中生成目录",
        "date": "2022-02-13T00:00:00.000Z",
        "tags": [
          "mk"
        ],
        "categories": [
          "markdown"
        ]
      },
      "regularPath": "/blogs/category/markdown/toc.html",
      "relativePath": "blogs/category/markdown/toc.md",
      "key": "v-740468a1",
      "path": "/blogs/category/markdown/toc.html",
      "lastUpdated": "2/14/2022, 9:57:12 PM"
    },
    {
      "title": "Echarts给字体加阴影,描边颜色",
      "frontmatter": {
        "title": "Echarts给字体加阴影,描边颜色",
        "date": "2022-02-25T00:00:00.000Z",
        "tags": [
          "echarts"
        ],
        "categories": [
          "Echarts"
        ]
      },
      "regularPath": "/blogs/category/echarts/shadow.html",
      "relativePath": "blogs/category/echarts/shadow.md",
      "key": "v-4a4ab1bb",
      "path": "/blogs/category/echarts/shadow.html"
    },
    {
      "title": "Vue进阶-在vue项目中封装自己的插件",
      "frontmatter": {
        "title": "Vue进阶-在vue项目中封装自己的插件",
        "date": "2022-01-07T00:00:00.000Z",
        "tags": [
          "Vue"
        ],
        "categories": [
          "Vue"
        ]
      },
      "regularPath": "/blogs/category/Vue/vueInstall.html",
      "relativePath": "blogs/category/Vue/vueInstall.md",
      "key": "v-08f12e1b",
      "path": "/blogs/category/Vue/vueInstall.html",
      "headers": [
        {
          "level": 2,
          "title": "前奏",
          "slug": "前奏"
        },
        {
          "level": 2,
          "title": "主题",
          "slug": "主题"
        },
        {
          "level": 2,
          "title": "总结",
          "slug": "总结"
        },
        {
          "level": 2,
          "title": "鸡汤时刻",
          "slug": "鸡汤时刻"
        }
      ],
      "excerpt": "<div class=\"custom-block tip\"><p class=\"title\"></p><p>这是一篇关于在Vue项目中开发自定义插件的文章o(<em>￣︶￣</em>)o</p>\n</div>",
      "lastUpdated": "2/8/2022, 11:10:03 AM"
    },
    {
      "title": "git常用命令",
      "frontmatter": {
        "title": "git常用命令",
        "date": "2022-01-14T00:00:00.000Z",
        "tags": [
          "git"
        ],
        "categories": [
          "Git"
        ],
        "sticky": 2
      },
      "regularPath": "/blogs/category/git/gitcmd.html",
      "relativePath": "blogs/category/git/gitcmd.md",
      "key": "v-d084738a",
      "path": "/blogs/category/git/gitcmd.html",
      "headers": [
        {
          "level": 3,
          "title": "提交暂存区",
          "slug": "提交暂存区"
        },
        {
          "level": 3,
          "title": "提交本地仓库",
          "slug": "提交本地仓库"
        },
        {
          "level": 3,
          "title": "关联远程仓库",
          "slug": "关联远程仓库"
        },
        {
          "level": 3,
          "title": "推送到远程仓库,第一次推送要写远程分支的名字,推送成功后,后面直接git push就行了",
          "slug": "推送到远程仓库-第一次推送要写远程分支的名字-推送成功后-后面直接git-push就行了"
        },
        {
          "level": 3,
          "title": "查看远程仓库地址",
          "slug": "查看远程仓库地址"
        },
        {
          "level": 3,
          "title": "撤销本次git add .",
          "slug": "撤销本次git-add"
        },
        {
          "level": 3,
          "title": "撤销本次git commit不撤销add",
          "slug": "撤销本次git-commit不撤销add"
        },
        {
          "level": 3,
          "title": "git 移除",
          "slug": "git-移除"
        },
        {
          "level": 3,
          "title": "git 创建分支",
          "slug": "git-创建分支"
        },
        {
          "level": 3,
          "title": "git 查看当前分支",
          "slug": "git-查看当前分支"
        },
        {
          "level": 3,
          "title": "git 查看历史提交记录",
          "slug": "git-查看历史提交记录"
        },
        {
          "level": 3,
          "title": "git 克隆项目",
          "slug": "git-克隆项目"
        },
        {
          "level": 3,
          "title": "git查看距离上一次提交到目前你做过的改动",
          "slug": "git查看距离上一次提交到目前你做过的改动"
        },
        {
          "level": 3,
          "title": "git合并分支",
          "slug": "git合并分支"
        },
        {
          "level": 3,
          "title": "git 回到指定版本",
          "slug": "git-回到指定版本"
        },
        {
          "level": 3,
          "title": "下班之前你需要做的事情",
          "slug": "下班之前你需要做的事情"
        },
        {
          "level": 2,
          "title": "遇到的一些问题",
          "slug": "遇到的一些问题"
        },
        {
          "level": 3,
          "title": "vscode插件推荐",
          "slug": "vscode插件推荐"
        },
        {
          "level": 2,
          "title": "结束语",
          "slug": "结束语"
        }
      ],
      "excerpt": "<div class=\"custom-block tip\"><p class=\"title\"></p><p>这是一篇关于git常用命令的文档o(￣▽￣)ｄ</p>\n</div>",
      "lastUpdated": "2/22/2022, 9:27:56 PM"
    },
    {
      "title": "Echarts字体自适应",
      "frontmatter": {
        "title": "Echarts字体自适应",
        "date": "2022-02-16T00:00:00.000Z",
        "tags": [
          "echarts"
        ],
        "categories": [
          "Echarts"
        ]
      },
      "regularPath": "/blogs/category/echarts/fontsize.html",
      "relativePath": "blogs/category/echarts/fontsize.md",
      "key": "v-59a7318a",
      "path": "/blogs/category/echarts/fontsize.html",
      "headers": [
        {
          "level": 2,
          "title": "问题描述",
          "slug": "问题描述"
        },
        {
          "level": 2,
          "title": "解决方案",
          "slug": "解决方案"
        },
        {
          "level": 2,
          "title": "实际项目使用示例",
          "slug": "实际项目使用示例"
        }
      ],
      "lastUpdated": "2/19/2022, 11:05:19 PM"
    },
    {
      "title": "小程序学习之路三-网络请求的封装、tabbar、目录结构的了解",
      "frontmatter": {
        "title": "小程序学习之路三-网络请求的封装、tabbar、目录结构的了解",
        "date": "2022-02-21T00:00:00.000Z",
        "tags": [
          "miniProgram"
        ],
        "categories": [
          "miniProgram"
        ]
      },
      "regularPath": "/blogs/category/miniProgram/day3.html",
      "relativePath": "blogs/category/miniProgram/day3.md",
      "key": "v-cb27ab8a",
      "path": "/blogs/category/miniProgram/day3.html",
      "lastUpdated": "2/22/2022, 9:27:56 PM"
    },
    {
      "title": "微信小程序imgae标签无法撑满父容器",
      "frontmatter": {
        "title": "微信小程序imgae标签无法撑满父容器",
        "date": "2022-02-25T00:00:00.000Z",
        "tags": [
          "miniProgram"
        ],
        "categories": [
          "miniProgram"
        ]
      },
      "regularPath": "/blogs/category/miniProgram/record1.html",
      "relativePath": "blogs/category/miniProgram/record1.md",
      "key": "v-d9d5d85e",
      "path": "/blogs/category/miniProgram/record1.html",
      "headers": [
        {
          "level": 2,
          "title": "问题描述",
          "slug": "问题描述"
        },
        {
          "level": 2,
          "title": "解决方案",
          "slug": "解决方案"
        }
      ]
    },
    {
      "title": "小程序学习之路一-初识小程序",
      "frontmatter": {
        "title": "小程序学习之路一-初识小程序",
        "date": "2022-02-09T00:00:00.000Z",
        "tags": [
          "miniProgram"
        ],
        "categories": [
          "miniProgram"
        ]
      },
      "regularPath": "/blogs/category/miniProgram/day1.html",
      "relativePath": "blogs/category/miniProgram/day1.md",
      "key": "v-7dc222fb",
      "path": "/blogs/category/miniProgram/day1.html",
      "headers": [
        {
          "level": 2,
          "title": "注册账号",
          "slug": "注册账号"
        },
        {
          "level": 2,
          "title": "目录结构",
          "slug": "目录结构"
        },
        {
          "level": 2,
          "title": "Hello World",
          "slug": "hello-world"
        },
        {
          "level": 2,
          "title": "列表循环",
          "slug": "列表循环"
        },
        {
          "level": 2,
          "title": "总结",
          "slug": "总结"
        }
      ],
      "lastUpdated": "2/19/2022, 11:05:19 PM"
    },
    {
      "title": "我是如何在小程序中封装网络请求的",
      "frontmatter": {},
      "regularPath": "/blogs/category/miniProgram/request.html",
      "relativePath": "blogs/category/miniProgram/request.md",
      "key": "v-404148b3",
      "path": "/blogs/category/miniProgram/request.html",
      "headers": [
        {
          "level": 2,
          "title": "我是如何在小程序中封装网络请求的",
          "slug": "我是如何在小程序中封装网络请求的"
        },
        {
          "level": 2,
          "title": "方法一",
          "slug": "方法一"
        },
        {
          "level": 3,
          "title": "新建request.js文件",
          "slug": "新建request-js文件"
        },
        {
          "level": 3,
          "title": "新建login.js文件",
          "slug": "新建login-js文件"
        },
        {
          "level": 3,
          "title": "login页面使用示例",
          "slug": "login页面使用示例"
        }
      ],
      "lastUpdated": "2/22/2022, 9:27:56 PM"
    },
    {
      "title": "留言板",
      "frontmatter": {
        "title": "留言板",
        "date": "2022-01-14T00:00:00.000Z",
        "author": "夏鸣予",
        "publish": false
      },
      "regularPath": "/views/others/message.html",
      "relativePath": "views/others/message.md",
      "key": "v-36597502",
      "path": "/views/others/message.html",
      "lastUpdated": "2/3/2022, 9:57:18 PM"
    },
    {
      "title": "微信开发者工具关联gitee远程仓库",
      "frontmatter": {},
      "regularPath": "/blogs/category/miniProgram/gitee.html",
      "relativePath": "blogs/category/miniProgram/gitee.md",
      "key": "v-f15136a6",
      "path": "/blogs/category/miniProgram/gitee.html",
      "headers": [
        {
          "level": 2,
          "title": "微信开发者工具关联gitee远程仓库",
          "slug": "微信开发者工具关联gitee远程仓库"
        },
        {
          "level": 3,
          "title": "1.gitee上新建仓库",
          "slug": "_1-gitee上新建仓库"
        },
        {
          "level": 3,
          "title": "2.微信开发者工具上关联",
          "slug": "_2-微信开发者工具上关联"
        },
        {
          "level": 3,
          "title": "3.测试是否成功",
          "slug": "_3-测试是否成功"
        },
        {
          "level": 3,
          "title": "4.gitee上面检查一下",
          "slug": "_4-gitee上面检查一下"
        },
        {
          "level": 2,
          "title": "博客",
          "slug": "博客"
        }
      ],
      "lastUpdated": "2/22/2022, 9:27:56 PM"
    },
    {
      "title": "我的个人简介",
      "frontmatter": {
        "title": "我的个人简介",
        "date": "2022-01-14T00:00:00.000Z",
        "author": "夏鸣予",
        "tags": [
          "introduce"
        ],
        "sticky": 1
      },
      "regularPath": "/blogs/introduce/introduce.html",
      "relativePath": "blogs/introduce/introduce.md",
      "key": "v-8cfa1d18",
      "path": "/blogs/introduce/introduce.html",
      "headers": [
        {
          "level": 2,
          "title": "个人经历与简介",
          "slug": "个人经历与简介"
        },
        {
          "level": 2,
          "title": "爱好",
          "slug": "爱好"
        },
        {
          "level": 2,
          "title": "联系方式",
          "slug": "联系方式"
        },
        {
          "level": 2,
          "title": "结束语",
          "slug": "结束语"
        }
      ],
      "excerpt": "<div class=\"custom-block tip\"><p class=\"title\"></p><p>赏脸看看作者的个人简介把(￣︶￣)&gt;</p>\n</div>",
      "lastUpdated": "2/20/2022, 9:42:22 PM"
    },
    {
      "title": "小程序学习之路二-事件绑定",
      "frontmatter": {
        "title": "小程序学习之路二-事件绑定",
        "date": "2022-02-13T00:00:00.000Z",
        "tags": [
          "miniProgram"
        ],
        "categories": [
          "miniProgram"
        ]
      },
      "regularPath": "/blogs/category/miniProgram/day2.html",
      "relativePath": "blogs/category/miniProgram/day2.md",
      "key": "v-0c17269b",
      "path": "/blogs/category/miniProgram/day2.html",
      "headers": [
        {
          "level": 2,
          "title": "绑定事件",
          "slug": "绑定事件"
        },
        {
          "level": 2,
          "title": "总结",
          "slug": "总结"
        }
      ],
      "lastUpdated": "2/19/2022, 11:05:19 PM"
    },
    {
      "frontmatter": {
        "layout": "Tags",
        "title": "Tags"
      },
      "regularPath": "/tag/",
      "key": "v-b1564aac",
      "path": "/tag/"
    },
    {
      "frontmatter": {
        "layout": "FrontmatterKey",
        "title": "Categories"
      },
      "regularPath": "/categories/",
      "key": "v-ef9325c4",
      "path": "/categories/"
    },
    {
      "frontmatter": {
        "layout": "TimeLines",
        "title": "Timeline"
      },
      "regularPath": "/timeline/",
      "key": "v-6319eb4e",
      "path": "/timeline/"
    },
    {
      "frontmatter": {
        "layout": "Tag",
        "title": "js Tags"
      },
      "regularPath": "/tag/js/",
      "key": "v-e8d86dc8",
      "path": "/tag/js/"
    },
    {
      "frontmatter": {
        "layout": "Tag",
        "title": "ES6 Tags"
      },
      "regularPath": "/tag/ES6/",
      "key": "v-3257dcde",
      "path": "/tag/ES6/"
    },
    {
      "frontmatter": {
        "layout": "Tag",
        "title": "JavaScript Tags"
      },
      "regularPath": "/tag/JavaScript/",
      "key": "v-7a5f6990",
      "path": "/tag/JavaScript/"
    },
    {
      "frontmatter": {
        "layout": "Tag",
        "title": "Vue Tags"
      },
      "regularPath": "/tag/Vue/",
      "key": "v-32475d9a",
      "path": "/tag/Vue/"
    },
    {
      "frontmatter": {
        "layout": "Tag",
        "title": "axios Tags"
      },
      "regularPath": "/tag/axios/",
      "key": "v-980194ba",
      "path": "/tag/axios/"
    },
    {
      "frontmatter": {
        "layout": "Tag",
        "title": "mk Tags"
      },
      "regularPath": "/tag/mk/",
      "key": "v-e8d85932",
      "path": "/tag/mk/"
    },
    {
      "frontmatter": {
        "layout": "Tag",
        "title": "echarts Tags"
      },
      "regularPath": "/tag/echarts/",
      "key": "v-119ea9c2",
      "path": "/tag/echarts/"
    },
    {
      "frontmatter": {
        "layout": "Tag",
        "title": "git Tags"
      },
      "regularPath": "/tag/git/",
      "key": "v-32383f72",
      "path": "/tag/git/"
    },
    {
      "frontmatter": {
        "layout": "Tag",
        "title": "miniProgram Tags"
      },
      "regularPath": "/tag/miniProgram/",
      "key": "v-28201f4c",
      "path": "/tag/miniProgram/"
    },
    {
      "frontmatter": {
        "layout": "Tag",
        "title": "introduce Tags"
      },
      "regularPath": "/tag/introduce/",
      "key": "v-79a2a91a",
      "path": "/tag/introduce/"
    },
    {
      "frontmatter": {
        "layout": "Category",
        "title": "ES6 Categories"
      },
      "regularPath": "/categories/ES6/",
      "key": "v-7eff4a05",
      "path": "/categories/ES6/"
    },
    {
      "frontmatter": {
        "layout": "Category",
        "title": "JavaScript Categories"
      },
      "regularPath": "/categories/JavaScript/",
      "key": "v-081e6844",
      "path": "/categories/JavaScript/"
    },
    {
      "frontmatter": {
        "layout": "Category",
        "title": "Vue Categories"
      },
      "regularPath": "/categories/Vue/",
      "key": "v-7f0789a7",
      "path": "/categories/Vue/"
    },
    {
      "frontmatter": {
        "layout": "Category",
        "title": "axios Categories"
      },
      "regularPath": "/categories/axios/",
      "key": "v-2383bdd2",
      "path": "/categories/axios/"
    },
    {
      "frontmatter": {
        "layout": "Category",
        "title": "markdown Categories"
      },
      "regularPath": "/categories/markdown/",
      "key": "v-029715c2",
      "path": "/categories/markdown/"
    },
    {
      "frontmatter": {
        "layout": "Category",
        "title": "Echarts Categories"
      },
      "regularPath": "/categories/Echarts/",
      "key": "v-bd86249a",
      "path": "/categories/Echarts/"
    },
    {
      "frontmatter": {
        "layout": "Category",
        "title": "Git Categories"
      },
      "regularPath": "/categories/Git/",
      "key": "v-7f008cdb",
      "path": "/categories/Git/"
    },
    {
      "frontmatter": {
        "layout": "Category",
        "title": "miniProgram Categories"
      },
      "regularPath": "/categories/miniProgram/",
      "key": "v-e6d4b880",
      "path": "/categories/miniProgram/"
    },
    {
      "frontmatter": {
        "layout": "Layout",
        "title": "Page 2 - js | Tags"
      },
      "regularPath": "/tag/js/page/2/",
      "key": "v-5bf9d5be",
      "path": "/tag/js/page/2/"
    }
  ],
  "themeConfig": {
    "subSidebar": "auto",
    "author": "夏鸣予",
    "huawei": true,
    "nav": [
      {
        "text": "首页",
        "link": "/",
        "icon": "reco-home"
      },
      {
        "text": "外链",
        "icon": "reco-document",
        "items": [
          {
            "text": "ES6",
            "link": "https://es6.ruanyifeng.com/"
          },
          {
            "text": "toutiao-pc",
            "link": "https://www.bilibili.com/video/BV1Pq4y1S7jm?spm_id_from=333.999.0.0"
          },
          {
            "text": "尚品汇商城",
            "link": "https://www.bilibili.com/video/BV1Vf4y1T7bw?from=search&seid=5678779092951775180&spm_id_from=333.337.0.0"
          }
        ]
      },
      {
        "text": "时间轴",
        "link": "/timeline/",
        "icon": "reco-date"
      },
      {
        "text": "留言板",
        "icon": "reco-message",
        "link": "/views/others/message"
      },
      {
        "text": "Contact",
        "icon": "reco-message",
        "items": [
          {
            "text": "gitee",
            "link": "https://gitee.com/smart-x",
            "icon": "reco-mayun"
          },
          {
            "text": "csdn",
            "link": "https://blog.csdn.net/qq_42356513?spm=1011.2124.3001.5343",
            "icon": "reco-csdn"
          }
        ]
      }
    ],
    "valineConfig": {
      "appId": "3LHlTn3FClOQQwfLAMUuucTc-gzGzoHsz",
      "appKey": "xp6lSBicUhJOY3LLQIEPIYEv"
    },
    "sidebar": {
      "/docs/theme-reco/": [
        "",
        "theme",
        "plugin",
        "api"
      ]
    },
    "type": "blog",
    "blogConfig": {
      "category": {
        "location": 2,
        "text": "知识"
      },
      "tag": {
        "location": 3,
        "text": "标签"
      }
    },
    "friendLink": [
      {
        "title": "午后南杂",
        "desc": "Enjoy when you can, and endure when you must.",
        "email": "1156743527@qq.com",
        "link": "https://www.recoluan.com"
      },
      {
        "title": "vuepress-theme-reco",
        "desc": "A simple and beautiful vuepress Blog & Doc theme.",
        "avatar": "https://vuepress-theme-reco.recoluan.com/icon_vuepress_reco.png",
        "link": "https://vuepress-theme-reco.recoluan.com"
      }
    ],
    "logo": "/logo.png",
    "search": true,
    "searchMaxSuggestions": 10,
    "lastUpdated": "Last Updated",
    "authorAvatar": "/avatar.png",
    "recordLink": "https://beian.miit.gov.cn",
    "record": "浙ICP备2022002789号-1",
    "startYear": "2022"
  }
}