/**
 * Generated by "@vuepress/plugin-blog"
 */
export default {
  "tags": {
    "ES6": {
      "key": "ES6",
      "scope": "tags",
      "path": "/tag/ES6/",
      "pageKeys": [
        "v-b413a096"
      ]
    },
    "JavaScript": {
      "key": "JavaScript",
      "scope": "tags",
      "path": "/tag/JavaScript/",
      "pageKeys": [
        "v-b413a096"
      ]
    },
    "Vue": {
      "key": "Vue",
      "scope": "tags",
      "path": "/tag/Vue/",
      "pageKeys": [
        "v-dda97aca",
        "v-08f12e1b",
        "v-eb3e21ca",
        "v-9e11ec96",
        "v-71d07c7b"
      ]
    },
    "git": {
      "key": "git",
      "scope": "tags",
      "path": "/tag/git/",
      "pageKeys": [
        "v-d084738a"
      ]
    },
    "axios": {
      "key": "axios",
      "scope": "tags",
      "path": "/tag/axios/",
      "pageKeys": [
        "v-13ccba1b"
      ]
    },
    "introduce": {
      "key": "introduce",
      "scope": "tags",
      "path": "/tag/introduce/",
      "pageKeys": [
        "v-8cfa1d18"
      ]
    }
  },
  "categories": {
    "ES6": {
      "key": "ES6",
      "scope": "categories",
      "path": "/categories/ES6/",
      "pageKeys": [
        "v-b413a096"
      ]
    },
    "Vue": {
      "key": "Vue",
      "scope": "categories",
      "path": "/categories/Vue/",
      "pageKeys": [
        "v-dda97aca",
        "v-08f12e1b",
        "v-eb3e21ca",
        "v-9e11ec96",
        "v-71d07c7b"
      ]
    },
    "Git": {
      "key": "Git",
      "scope": "categories",
      "path": "/categories/Git/",
      "pageKeys": [
        "v-d084738a"
      ]
    },
    "axios": {
      "key": "axios",
      "scope": "categories",
      "path": "/categories/axios/",
      "pageKeys": [
        "v-13ccba1b"
      ]
    }
  },
  "timeline": {}
}