/**
 * Generated by "@vuepress/plugin-blog"
 */
export default {
  "tags": {
    "ES6": {
      "key": "ES6",
      "scope": "tags",
      "path": "/tag/ES6/",
      "pageKeys": [
        "v-cb115a0a",
        "v-b413a096",
        "v-04e1f27b"
      ]
    },
    "JavaScript": {
      "key": "JavaScript",
      "scope": "tags",
      "path": "/tag/JavaScript/",
      "pageKeys": [
        "v-cb115a0a",
        "v-b413a096",
        "v-04e1f27b"
      ]
    },
    "js": {
      "key": "js",
      "scope": "tags",
      "path": "/tag/js/",
      "pageKeys": [
        "v-6d1ffaaa",
        "v-c324f84a",
        "v-46ad39a7",
        "v-6319ebfb",
        "v-df4fc68a",
        "v-1b44d80e",
        "v-1c09b6fa",
        "v-543a3abe",
        "v-34331cbe"
      ]
    },
    "Vue": {
      "key": "Vue",
      "scope": "tags",
      "path": "/tag/Vue/",
      "pageKeys": [
        "v-62f1a805",
        "v-9e11ec96",
        "v-eb3e21ca",
        "v-dda97aca",
        "v-14e0f813",
        "v-99c196ca",
        "v-62e5d1fb",
        "v-08f12e1b",
        "v-71d07c7b"
      ]
    },
    "axios": {
      "key": "axios",
      "scope": "tags",
      "path": "/tag/axios/",
      "pageKeys": [
        "v-13ccba1b"
      ]
    },
    "echarts": {
      "key": "echarts",
      "scope": "tags",
      "path": "/tag/echarts/",
      "pageKeys": [
        "v-59a7318a"
      ]
    },
    "git": {
      "key": "git",
      "scope": "tags",
      "path": "/tag/git/",
      "pageKeys": [
        "v-d084738a"
      ]
    },
    "mk": {
      "key": "mk",
      "scope": "tags",
      "path": "/tag/mk/",
      "pageKeys": [
        "v-740468a1"
      ]
    },
    "introduce": {
      "key": "introduce",
      "scope": "tags",
      "path": "/tag/introduce/",
      "pageKeys": [
        "v-8cfa1d18"
      ]
    },
    "miniProgram": {
      "key": "miniProgram",
      "scope": "tags",
      "path": "/tag/miniProgram/",
      "pageKeys": [
        "v-7dc222fb",
        "v-0c17269b"
      ]
    }
  },
  "categories": {
    "ES6": {
      "key": "ES6",
      "scope": "categories",
      "path": "/categories/ES6/",
      "pageKeys": [
        "v-cb115a0a",
        "v-6d1ffaaa",
        "v-c324f84a",
        "v-b413a096",
        "v-04e1f27b",
        "v-6319ebfb",
        "v-df4fc68a"
      ]
    },
    "JavaScript": {
      "key": "JavaScript",
      "scope": "categories",
      "path": "/categories/JavaScript/",
      "pageKeys": [
        "v-46ad39a7",
        "v-1b44d80e",
        "v-1c09b6fa",
        "v-543a3abe",
        "v-34331cbe"
      ]
    },
    "Vue": {
      "key": "Vue",
      "scope": "categories",
      "path": "/categories/Vue/",
      "pageKeys": [
        "v-62f1a805",
        "v-9e11ec96",
        "v-eb3e21ca",
        "v-dda97aca",
        "v-14e0f813",
        "v-99c196ca",
        "v-62e5d1fb",
        "v-08f12e1b",
        "v-71d07c7b"
      ]
    },
    "axios": {
      "key": "axios",
      "scope": "categories",
      "path": "/categories/axios/",
      "pageKeys": [
        "v-13ccba1b"
      ]
    },
    "Echarts": {
      "key": "Echarts",
      "scope": "categories",
      "path": "/categories/Echarts/",
      "pageKeys": [
        "v-59a7318a"
      ]
    },
    "Git": {
      "key": "Git",
      "scope": "categories",
      "path": "/categories/Git/",
      "pageKeys": [
        "v-d084738a"
      ]
    },
    "markdown": {
      "key": "markdown",
      "scope": "categories",
      "path": "/categories/markdown/",
      "pageKeys": [
        "v-740468a1"
      ]
    },
    "miniProgram": {
      "key": "miniProgram",
      "scope": "categories",
      "path": "/categories/miniProgram/",
      "pageKeys": [
        "v-7dc222fb",
        "v-0c17269b"
      ]
    }
  },
  "timeline": {}
}