/**
 * Generated by "@vuepress/plugin-blog"
 */

import sorters from './pageSorters'
import filters from './pageFilters'

export default [{
  pid: "tags",
  id: "tag1",
  filter: filters.tags,
  sorter: sorters.tags,
  pages: [{"path":"/tag/tag1/","interval":[0,1]}],
  prevText: "Prev",
  nextText: "Next",
},
{
  pid: "tags",
  id: "Vue",
  filter: filters.tags,
  sorter: sorters.tags,
  pages: [{"path":"/tag/Vue/","interval":[0,2]}],
  prevText: "Prev",
  nextText: "Next",
},
{
  pid: "tags",
  id: "个人简介",
  filter: filters.tags,
  sorter: sorters.tags,
  pages: [{"path":"/tag/个人简介/","interval":[0,1]}],
  prevText: "Prev",
  nextText: "Next",
},
{
  pid: "tags",
  id: "git",
  filter: filters.tags,
  sorter: sorters.tags,
  pages: [{"path":"/tag/git/","interval":[0,1]}],
  prevText: "Prev",
  nextText: "Next",
},
{
  pid: "categories",
  id: "ES6",
  filter: filters.categories,
  sorter: sorters.categories,
  pages: [{"path":"/categories/ES6/","interval":[0,2]}],
  prevText: "Prev",
  nextText: "Next",
},
{
  pid: "categories",
  id: "Vue",
  filter: filters.categories,
  sorter: sorters.categories,
  pages: [{"path":"/categories/Vue/","interval":[0,2]}],
  prevText: "Prev",
  nextText: "Next",
},
{
  pid: "categories",
  id: "Git",
  filter: filters.categories,
  sorter: sorters.categories,
  pages: [{"path":"/categories/Git/","interval":[0,1]}],
  prevText: "Prev",
  nextText: "Next",
}]